### PR TITLE
[7.7.x] Remove task filter All

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by bsremac** [comment]
@cristianonicolai Is this the GA branch?

**Comment by cristianonicolai** [comment]
@bsremac yep

**Comment by bsremac** [comment]
@cristianonicolai Whatever is causing me build problems on #1015 is present here too.
Is it only me who is having build problems?
I even forked and build appformer from scratch.

**Comment by cristianonicolai** [comment]
@bsremac  I can't reproduce the same error on my local, could it be that the new master is on version 7.8.0 and your previous local build on appformer was using 7.7.0?

**Pull request merged**
