### PR TITLE
showcase fix after version updates

### PR DESCRIPTION
**Pull request by nmirasch**

### CODE REVIEW

**Comment by mbiarnes** [comment]
@manstis @danielezonca @gitgabrio 
this commit fixes the issue reposted by me about the jbpm-wb showcase. After she commited this locally jbpm-wb:showcase works. 
could you please look at this if it makes sense - because it could be this Nexus issue.

**Comment by manstis** [comment]
@mbiarnes Well...... if `jbpm-wb` never used to need `org.drools.workbench.models.commons.DroolsWorkbenchModelsCommon` then it is weird why it does now... AFAIK we've not changed any `gwt.xml` files so it's strange why GWT compilation now fails due to a missing GWT module.

**Comment by nmirasch** [comment]
@manstis absolutely agree. It's weird

**Comment by mbiarnes** [comment]
@manst @nmirasch there is a PR in droolsjbpm-build-bootstrap right now (full downstream build) https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/987  - if this doesn't fail in jbpm-wb:showcase and in other two Jenkins builds (running right now) don't fail we should close this PR.

**Comment by mbiarnes** [comment]
one Jenkins job failed because of the GWT module:
https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/Test-jobs/job/mbiarnes_updateVersion_tests/3/console - lets see the other

**Comment by mbiarnes** [comment]
the other too: https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/dailyBuild/job/kieAllBuild-master/31/console - same failure
So this is a kind of un-understandable error - but it seems that this PR solves this

**Comment by mbiarnes** [comment]
@manstis can't find any! 
But if the full downstream fails at jbpm-wb:showcase I will merge this. At least weh have master green.

**Comment by gitgabrio** [comment]
@manstis @mbiarnes 

This is results on my machine:

`(cd folder with all projects)
 grep --include=*.gwt.xml -rnw '.' -e 'org.drools.workbench.models.commons.DroolsWorkbenchModelsCommon' 

.....

./kie-wb-common/kie-wb-common-widgets/kie-wb-common-ui/src/main/resources/org/kie/workbench/common/widgets/KieWorkbenchWidgetsCommon.gwt.xml:38:  <inherits name="org.drools.workbench.models.commons.DroolsWorkbenchModelsCommon"/>

.....

cd jbpm-wb/jbpm-wb-showcase

mvn dependency:tree -Dincludes=org.kie.workbench.widgets:kie-wb-common-ui

[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------------< org.jbpm:jbpm-wb-showcase >----------------------
[INFO] Building jBPM Workbench - Showcase 7.24.0-SNAPSHOT
[INFO] --------------------------------[ war ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:3.1.1:tree (default-cli) @ jbpm-wb-showcase ---
[INFO] org.jbpm:jbpm-wb-showcase:war:7.24.0-SNAPSHOT
[INFO] \- org.kie.workbench.widgets:kie-wb-common-ui:jar:7.24.0-SNAPSHOT:provided
`
I'm not sure about your doubts, nor if my machine exactly reflect current status, but it seems that  _jbpm-wb-showcase_ **depend** (=_maven inheritance_) on _kie-wb-common-ui_ that in turns **inherit** (=_GWT inheritance_) _org.drools.workbench.models.commons.DroolsWorkbenchModelsCommon_. Anyway this procedure should identify. It maybe a different inherit module, or even an indirect inherited one.

**Pull request merged**
