### PR TITLE
JBPM-7465 Process Instances: Process variables as columns should be a…

### PR DESCRIPTION
**Pull request by bxf12315**
…dded to the left of Actions column

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@bxf12315 add a test and please also make sure you always make it clear that there is a related/dependent PR. Merging one and not the other can cause issues on breaking a branch compilation.

**Comment by bxf12315** [comment]
@cristianonicolai  I added unit in the PR https://github.com/kiegroup/appformer/pull/525.
The PR dependent PR https://github.com/kiegroup/appformer/pull/525. 
Please review it.

**Comment by cristianonicolai** [comment]
@bxf12315 could one test be added here to ensure the visible index value for the action column?

**Comment by bxf12315** [comment]
@cristianonicolai  I am not sure I can add test in here.
I can take a try.

**Comment by bxf12315** [comment]
@cristianonicolai  AFAIK, The feature that  add or remove column on datagrid , not belong to here, it belong to appformer's feature.

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Pull request merged**
