### PR TITLE
JBPM-7817 - Data set editor shows 'supports expression reference $nul…

### PR DESCRIPTION
**Pull request by MarianMacik**
…l' as a hint

Please see the [JIRA](https://issues.jboss.org/browse/JBPM-7817) for an explanation.

Can I test it somehow to be 100% sure? Maybe full downstream build would help?

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@MarianMacik yep, a full downstream build can help, using the single zip dist to test.

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by MarianMacik** [comment]
I have verified it and it works now correctly. So can I merge this branch?

**Comment by cristianonicolai** [comment]
@MarianMacik thanks

**Pull request merged**
