### PR TITLE
JBPM-7807 - Add support for node instances admin operations

### PR DESCRIPTION
**Pull request by cristianonicolai**
Depends on https://github.com/kiegroup/jbpm-wb/pull/1247

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@nmirasch @jsoltes adding support for node instances cancel and retrigger operations. Will rebase once https://github.com/kiegroup/jbpm-wb/pull/1247 is merged.

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by jsoltes** [comment]
@cristianonicolai I have also found one bug on the ui:
When I retrigger an (active) human tasks, I see two new node instances one with the same Id and one with id raised by 1. The second one with the same id opens the previous one. I have recorded the situation in the attached video.
[retrigger.zip](https://github.com/kiegroup/jbpm-wb/files/2648981/retrigger.zip)

**Comment by cristianonicolai** [comment]
Closing PR as changes are incorporated into https://github.com/kiegroup/jbpm-wb/pull/1250

**Pull request closed without merging**
