### PR TITLE
[7.11.x] JBPM-7817 - Data set editor shows 'supports expression reference $nul…

### PR DESCRIPTION
**Pull request by MarianMacik**
…l' as a hint

Backport of #1211

### CODE REVIEW

**Comment by MarianMacik** [comment]
jenkins execute full downstream build

**Comment by cristianonicolai** [comment]
@MarianMacik it should be blockers only on this branch.

**Comment by MarianMacik** [comment]
@cristianonicolai and what about patches?

**Comment by MarianMacik** [comment]
As discussed with @cristianonicolai, this will be included in the next minor release. Closing.

**Pull request closed without merging**
