### PR TITLE
JBPM-8730 Filters - numeric field hint not in sync with implementation

### PR DESCRIPTION
**Pull request by bxf12315**
@cristianonicolai Please review it .

### CODE REVIEW

**Comment by jstastny-cz** [comment]
Jenkins execute full downstream build

**Comment by jstastny-cz** [comment]
@bxf12315 you should put JBPM jiras to the PRs, RHPAM is not publicly available.

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by cristianonicolai** [comment]
@jstastny-cz @nmirasch please take a look.

**Comment by krisv** [comment]
@jstastny-cz in general it's fine to use RHPAM/RHDM references in commits, they are (in almost all cases) public (although if a team wants to have the habbit of also reporting it as an upstream issue that's of course fine too).

**Comment by jstastny-cz** [comment]
@krisv ok, though in this case there was no JBPM jira in that time, is that expected?

**Pull request merged**
