### PR TITLE
RHPAM-4455 org.w3c:dom dependency to jbpm-wb

### PR DESCRIPTION
**Pull request by bxf12315**
**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[https://issues.redhat.com/browse/RHPAM-4455](https://issues.redhat.com/browse/RHPAM-4455)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by bxf12315** [comment]
Jenkins retest this

**Comment by bxf12315** [comment]
Jenkins retest this

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
@bxf12315 please fix the merge conflicts

**Comment by bxf12315** [comment]
@mareknovotny I think PR https://github.com/kiegroup/jbpm-wb/pull/1567 also can fix the issue, I will close this one.

**Comment by Ginxo** [comment]
> @mareknovotny I think PR #1567 also can fix the issue, I will close this one.

w3c:dom library doesn't seem to be needed, right? I would suggest to close this in favor of https://github.com/kiegroup/jbpm-wb/pull/1567 set, wdyt? @bxf12315

**Comment by Ginxo** [comment]
the jbpm-designer removal has been removed from https://github.com/kiegroup/jbpm-wb/pull/1563 so the additional xml-apis removal is not required

**Comment by Ginxo** [comment]
@bxf12315 do you agree on closing this since https://github.com/kiegroup/jbpm-wb/pull/1567 has been merged? thanks

**Comment by mareknovotny** [comment]
closing as this is not mergeble and still we already merged #1567

**Pull request closed without merging**
