### PR TITLE
JBPM-5799 - New assembly distribution for EAP7 and WildFly 10

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@bsremac could you take a look on this one.

**Comment by bsremac** [comment]
@cristianonicolai I've been able to successfully deploy Casey.war along with kie-wb.war and kie-server.war without any problems. Case definitions are properly shown in Casey, but the same problem with case list access exists as in #655.

**Comment by cristianonicolai** [comment]
@bsremac sure, I still trying to identify that problem in the other PR. Would you be happy to approve this one then?

**Comment by bsremac** [comment]
+1

**Pull request merged**
