### PR TITLE
JBPM-5687: Error messages for missing jBPM capability

### PR DESCRIPTION
**Pull request by karreiro**
See https://issues.jboss.org/browse/JBPM-5687 and https://github.com/dashbuilder/dashbuilder/pull/337

Before:
task-error
process-error
dashboard-error

After:
screen shot 2017-05-25 at 6 33 38 pm
screen shot 2017-05-25 at 6 32 27 pm
screen shot 2017-05-25 at 6 32 58 pm
screen shot 2017-05-25 at 6 33 58 pm

### CODE REVIEW

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by karreiro** [comment]
@cristianonicolai Could you please take a look? :-)

**Comment by cristianonicolai** [comment]
@karreiro looks good to me, if you don't mind, could you rebase your change once https://github.com/kiegroup/jbpm-wb/pull/753 is merged?

**Comment by karreiro** [comment]
@cristianonicolai yes, no problem. :-)

**Comment by karreiro** [comment]
@cristianonicolai Done! Could please approve and merge this one? (it's important to merge this one too https://github.com/dashbuilder/dashbuilder/pull/337) :-)

**Comment by cristianonicolai** [comment]
@karreiro https://github.com/dashbuilder/dashbuilder/pull/337 got merged but this one had conflicting commits merged that require another rebase.

**Comment by karreiro** [comment]
Jenkins, please restest this.

**Comment by karreiro** [comment]
Jenkins, please retest this.

**Comment by karreiro** [comment]
Could you please merge this @cristianonicolai?

**Comment by cristianonicolai** [comment]
@karreiro done, thanks!

**Pull request merged**
