### PR TITLE
AF-559: replaced mangedexecutorservice with ExecutorService

### PR DESCRIPTION
**Pull request by adrielparedes**
description: https://github.com/AppFormer/uberfire/pull/761

### CODE REVIEW

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by adrielparedes** [comment]
Jenkins execute full downstream build

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by adrielparedes** [comment]
jenkins retest this

**Comment by adrielparedes** [comment]
Jenkins execute full downstream build

**Comment by adrielparedes** [comment]
Jenkins execute full downstream build

**Pull request merged**
