### PR TITLE
[JBPM-9777] Enrich information of jbpmHumanTasksWithAdmin default query

### PR DESCRIPTION
**Pull request by elguardian**
Jira : https://issues.redhat.com/browse/JBPM-9777

### CODE REVIEW

**Review by gmunozfe — CHANGES_REQUESTED** [review]
Missing formname and lastuser

**Comment by elguardian** [comment]
Jenkins retest this

**Review by gmunozfe — APPROVED** [review]
Looks good to me, awesome job @elguardian !

**Comment by gmunozfe** [comment]
@elguardian, One more thing: for completeness, could you include a test case into [KieServerQueryDefinitionLoaderTest.java](https://github.com/kiegroup/jbpm-wb/blob/27a4318b4ca03298ad7c56c20f10c8b4135085da/jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/test/java/org/jbpm/workbench/ks/integration/KieServerQueryDefinitionLoaderTest.java#L182)?

**Comment by elguardian** [comment]
Jenkins retest this please

**Comment by elguardian** [comment]
Jenkins retest this please

**Comment by elguardian** [comment]
Jenkins retest this please

**Comment by elguardian** [comment]
Jenkins retest this please

**Comment by elguardian** [comment]
Jenkins retest this please

**Pull request merged**
