### PR TITLE
BXMSPROD-2081: Remove PLANNING capability (#1547)

### PR DESCRIPTION
**Pull request by mbiarnes**
(cherry picked from commit 2e11eb47b82d57c95ad3502c8329135d62d4efcd)

**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[BXMSPROD-2081](https://issues.redhat.com/browse/BXMSPROD-2081)

** https://github.com/kiegroup/kie-wb-distributions/pull/1230
** https://github.com/kiegroup/jbpm-wb/pull/1599
** https://github.com/kiegroup/droolsjbpm-integration/pull/2977
** https://github.com/kiegroup/kie-wb-common/pull/3814
** https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2344

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

**Comment by mbiarnes** [comment]
Jenkins retest this

**Review by lampajr — APPROVED** [review]

**Comment by lampajr** [comment]
There is an issue on gha:
```
2023-07-06T14:45:28.6571236Z /home/runner/work/jbpm-wb/jbpm-wb/kiegroup_jbpm-work-items/jbpm-workitem-itests/src/test/java/org/jbpm/workitem/springboot/samples/KafkaSampleTest.java:[37,33] cannot access io.strimzi.test.container.StrimziKafkaContainer
2023-07-06T14:45:28.6592299Z   bad class file: /home/runner/.m2/repository/io/strimzi/strimzi-test-container/0.104.0/strimzi-test-container-0.104.0.jar(io/strimzi/test/container/StrimziKafkaContainer.class)
2023-07-06T14:45:28.6592854Z     class file has wrong version 55.0, should be 52.0
2023-07-06T14:45:28.6593425Z     Please remove or make sure it appears in the correct subdirectory of the classpath.
2023-07-06T14:45:28.6594017Z 
2023-07-06T14:45:28.6594503Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
2023-07-06T14:45:28.6616400Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
2023-07-06T14:45:28.6617125Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
```

@Ginxo seems related to https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2334
weird thing is that only gha is failing, jenkins checks are fine

**Comment by Ginxo** [comment]
so It seems java8 is not compatible, right?

**Comment by lampajr** [comment]
> so It seems java8 is not compatible, right?

it seems so, on java 11 check there is a different issue so yeah I think it could be the reason

**Comment by Ginxo** [comment]
FYI
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2346

**Comment by mbiarnes** [comment]
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2347 and subset of PRs take a fixed version for OptaPlanner

**Pull request closed without merging**
