### PR TITLE
RHPAM-3432: [Stunner] Case Definition - Wrong location of the default WID file 

### PR DESCRIPTION
**Pull request by hasys**
**JIRA**: [RHPAM-3432](https://issues.redhat.com/browse/RHPAM-3432)

**WAR**: [Business Central](https://drive.google.com/file/d/17W0nKBfaTyxn_YcxQTyEDJWfgF8c6PlV/view?usp=sharing)

Hello @romartin, @LuboTerifaj, as discussed this PR is a cherry-pick of both 
* [JBPM-9568 - Case Definition - Wrong location of the default WID file](https://github.com/kiegroup/jbpm-wb/pull/1477)
* [JBPM-9601: Stunner - Business Rule and Decision tasks are missing in Case Project by default](https://github.com/kiegroup/jbpm-wb/pull/1478)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by hasys** [comment]
jenkins do cdb

**Review by romartin — APPROVED** [review]

**Comment by hasys** [comment]
jenkins do cdb

**Comment by hasys** [comment]
jenkins do cdb

**Comment by hasys** [comment]
jenkins do cdb

**Comment by hasys** [comment]
jenkins do cdb

**Review by LuboTerifaj — APPROVED** [review]
It looks good to me.

**Comment by hasys** [comment]
Full compile build failed due to missing space:

<details>
  <summary>Stacktrace</summary>
  <pre>java.nio.file.FileSystemException: /home/jenkins/workspace/KIE/7.48.x: No space left on device
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:767)
	at hudson.FilePath.mkdirs(FilePath.java:3273)
	at hudson.FilePath.access$1300(FilePath.java:213)
	at hudson.FilePath$Mkdirs.invoke(FilePath.java:1254)
	at hudson.FilePath$Mkdirs.invoke(FilePath.java:1250)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3086)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)</pre>
</details>

**Comment by hasys** [comment]
jenkins do cdb

**Comment by romartin** [comment]
@hasys lemme know when it's ready to be merged. Thx!

**Comment by hasys** [comment]
jenkins do cdb

**Comment by hasys** [comment]
jenkins do cdb

**Pull request merged**
