### PR TITLE
JBPM-8263 - Handle missing SVG image

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@jstastny-cz handling the fact that the image is not there, but still doesn't explain why the image couldnt be found.

**Comment by jstastny-cz** [comment]
I noticed another thing, there seems to be an alert div with error message in the div #processDiagramDiv, shouldn't it be presented to the user?
screenshot from 2019-02-20 08-58-01

**Comment by cristianonicolai** [comment]
@jstastny-cz yep, that is expected and at least to me it shows correctly as:

selection_015

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by cristianonicolai** [comment]
@jstastny-cz you're right, I can see that in the final build the alert message is not displayed. Will open a specific bug for that.

**Comment by cristianonicolai** [comment]
https://issues.jboss.org/browse/JBPM-8274

**Comment by cristianonicolai** [comment]
@jstastny-cz happy for this to be merged? The missing alert message will be handled in a different JIRA.

**Pull request merged**
