### PR TITLE
JBPM-9601: Stunner - Business Rule and Decision tasks are missing in Case Project by default

### PR DESCRIPTION
**Pull request by hasys**
**Thank you for submitting this pull request**

**JIRA**: [JBPM-9601](https://issues.redhat.com/browse/JBPM-9601)

**Business Central**: [WAR](https://drive.google.com/file/d/1Yy6azr5QxYlITlTH0caHS0st_uBbx83P/view?usp=sharing)

Hi @romartin, @LuboTerifaj, there is an update of Case Project WID file. It adds only Business Rule and Decision tasks as discussed.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by hasys** [comment]
jenkins do cdb

**Comment by hasys** [comment]
Build fail is unrelated, retriggering

<details>
  <summary>Console log</summary>
  <pre>11:52:29  [INFO] BUILD FAILURE
11:52:29  [INFO] ------------------------------------------------------------------------
11:52:29  [INFO] Total time:  21.990 s (Wall Clock)
11:52:29  [INFO] Finished at: 2021-02-16T06:49:14-05:00
11:52:29  [INFO] ------------------------------------------------------------------------
11:52:29  [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project google-sheets-workitem: Compilation failure: Compilation failure: 
11:52:29  [ERROR] error reading /home/jenkins/.m2/repository/com/google/http-client/google-http-client/1.23.0/google-http-client-1.23.0.jar; zip file is empty
11:52:29  [ERROR] error reading /home/jenkins/.m2/repository/com/google/http-client/google-http-client/1.23.0/google-http-client-1.23.0.jar; zip file is empty
11:52:29  [ERROR] /home/jenkins/workspace/KIE/master/pullrequest/jbpm-wb-master.pr/kiegroup_jbpm-work-items/google-sheets-workitem/target/generated-sources/java/org/jbpm/process/workitem/google/sheets/GoogleSheetsAuth.java:[27,34] package com.google.api.client.http does not exist
11:52:29  [ERROR] /home/jenkins/workspace/KIE/master/pullrequest/jbpm-wb-master.pr/kiegroup_jbpm-work-items/google-sheets-workitem/target/generated-sources/java/org/jbpm/process/workitem/google/sheets/GoogleSheetsAuth.java:[28,34] package com.google.api.client.json does not exist
11:52:29  [ERROR] /home/jenkins/workspace/KIE/master/pullrequest/jbpm-wb-master.pr/kiegroup_jbpm-work-items/google-sheets-workitem/target/generated-sources/java/org/jbpm/process/workitem/google/sheets/GoogleSheetsAuth.java:[35,26] cannot find symbol
11:52:29  [ERROR]   symbol:   class JsonFactory
11:52:29  [ERROR]   location: class org.jbpm.process.workitem.google.sheets.GoogleSheetsAuth
11:52:29  [ERROR] /home/jenkins/workspace/KIE/master/pullrequest/jbpm-wb-master.pr/kiegroup_jbpm-work-items/google-sheets-workitem/target/generated-sources/java/org/jbpm/process/workitem/google/sheets/GoogleSheetsAuth.java:[36,20] cannot find symbol
11:52:29  [ERROR]   symbol:   class HttpTransport
11:52:29  [ERROR]   location: class org.jbpm.process.workitem.google.sheets.GoogleSheetsAuth
11:52:29  [ERROR] -> [Help 1]
11:52:29  org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project google-sheets-workitem: Compilation failure
11:52:29      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
11:52:29      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
11:52:29      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
11:52:29      at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
11:52:29      at io.takari.maven.builder.smart.SmartBuilderImpl.buildProject (SmartBuilderImpl.java:205)
11:52:29      at io.takari.maven.builder.smart.SmartBuilderImpl$ProjectBuildTask.run (SmartBuilderImpl.java:77)
11:52:29      at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
11:52:29      at java.util.concurrent.FutureTask.run (FutureTask.java:266)
11:52:29      at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
11:52:29      at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
11:52:29      at java.lang.Thread.run (Thread.java:748)
11:52:29  Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
11:52:29      at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute (AbstractCompilerMojo.java:1220)
11:52:29      at org.apache.maven.plugin.compiler.CompilerMojo.execute (CompilerMojo.java:187)
11:52:29      at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
11:52:29      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
11:52:29      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
11:52:29      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
11:52:29      at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
11:52:29      at io.takari.maven.builder.smart.SmartBuilderImpl.buildProject (SmartBuilderImpl.java:205)
11:52:29      at io.takari.maven.builder.smart.SmartBuilderImpl$ProjectBuildTask.run (SmartBuilderImpl.java:77)
11:52:29      at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
11:52:29      at java.util.concurrent.FutureTask.run (FutureTask.java:266)
11:52:29      at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
11:52:29      at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
11:52:29      at java.lang.Thread.run (Thread.java:748)</pre>
</details>

**Comment by hasys** [comment]
Jenkins retest this

**Review by romartin — APPROVED** [review]

**Comment by romartin** [comment]
great, thanks   @hasys , as commented let's just synchronize the file :+1: 
Approved.

**Review by LuboTerifaj — APPROVED** [review]
Hello @hasys ,

there is only one issue with missing icons for these tasks. I think it should be fixed in this jira: https://issues.redhat.com/browse/JBPM-9602

Approving.

Thank you!

**Pull request merged**
