### PR TITLE
Move common PatternFly related Errai UI components from jbpm-wb to ub…

### PR DESCRIPTION
**Pull request by cristianonicolai**
…erfire

### CODE REVIEW

**Comment by cristianonicolai** [comment]
Depends on https://github.com/AppFormer/uberfire/pull/706

**Comment by cristianonicolai** [comment]
Jenkins please retest this.

**Comment by nmirasch** [comment]
@cristianonicolai  Just a quick question, Do you think is a good moment to put the converters to a common place too? (DateConverter, CommaListValues)

**Comment by cristianonicolai** [comment]
@nmirasch just not sure where to be honest. @ederign do you have any suggestion to where we could move utility classes for Errai (Converter)?

**Comment by cristianonicolai** [comment]
@nmirasch @ederign independently from moving the converters this PR still valid. That would be done as separated commit.

**Pull request merged**
