### PR TITLE
[DROOLS-2152] fixes after mockito upgrade

### PR DESCRIPTION
**Pull request by psiroky**
Depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/622

### CODE REVIEW

**Comment by psiroky** [comment]
Just a few more failing tests without obvious fix (or I could not find one). @cristianonicolai or @nmirasch would you able to take a look?

**Comment by cristianonicolai** [comment]
@psiroky I will take a look as soon as possible, thanks

**Comment by cristianonicolai** [comment]
@psiroky added fixes in PR here: https://github.com/psiroky/jbpm-console-ng/pull/1

**Comment by cristianonicolai** [comment]
@psiroky there is one missing fix that needs to go in dashbuilder, see: 
`Following stubbings are unnecessary (click to navigate to relevant line of code):
  1. -> at org.dashbuilder.displayer.client.AbstractDisplayerTest.init(AbstractDisplayerTest.java:53)`

**Comment by psiroky** [comment]
Closing the PR as I won't be able to work on this and there are still some related PRs not completely done. I am keeping the branch around in case someone else would like to pick this up.

**Comment by cristianonicolai** [comment]
@jhrcek @bsremac any chance you guys could take a look on this?

**Comment by bsremac** [comment]
@cristianonicolai From QE side we can take a look at failing tests and help in fixing them (that being the appropriate QE per project) after upgrade of tools/frameworks, but we can't drive the upgrade process itself. 

Making changes in _droolsjbpm-build-bootstrap_  and resolving all potential build/dependencies conflicts in all projects should be handled by someone more experienced.

**Pull request closed without merging**
