### PR TITLE
[7.59.x] JBPM-9896 - Fix dependency for compilation Stunner on JDK 11 to JRE 8 

### PR DESCRIPTION
**Pull request by hasys**
Hi @mareknovotny, @mbiarnes, @romartin, @jomarko it is cherry-pick of https://github.com/kiegroup/jbpm-wb/pull/1513

**referenced Pull Requests**: 

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1771
* https://github.com/kiegroup/kie-wb-distributions/pull/1129
* https://github.com/kiegroup/jbpm-wb/pull/1515
* https://github.com/kiegroup/kie-wb-common/pull/3685

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by jomarko — APPROVED** [review]

**Review by mbiarnes — APPROVED** [review]
+1

**Comment by mbiarnes** [comment]
two tests failed: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/7.59.x/job/pullrequest/job/jbpm-wb-7.59.x.pr/2/testReport/

**Comment by hasys** [comment]
Deployment tests failed which is unrelated to SVG generation on client side.

I suggest to proceed without retrigger, WDYT @mareknovotny, @mbiarnes, @romartin, @jomarko ?
```
    org.jbpm.workbench.cm.DeploymentIT.org.jbpm.workbench.cm.DeploymentIT
    org.jbpm.workbench.DeploymentIT.testCaseManagementDeployment
```

**Comment by mareknovotny** [comment]
i reported https://issues.redhat.com/browse/JBPM-9899 to show that the 2 failures are on 7.59.x branch too without this PR change

**Review by romartin — APPROVED** [review]

**Pull request merged**
