### PR TITLE
[7.3.x] Home icon fix

### PR DESCRIPTION
**Pull request by paulovmr**

### CODE REVIEW

**Comment by paulovmr** [comment]
Part of an ensemble:
* https://github.com/kiegroup/kie-wb-common/pull/1102
* https://github.com/kiegroup/drools-wb/pull/587
* https://github.com/kiegroup/jbpm-form-modeler/pull/139
* https://github.com/kiegroup/jbpm-wb/pull/857
* https://github.com/kiegroup/optaplanner-wb/pull/210
* https://github.com/kiegroup/kie-wb-distributions/pull/604

**Comment by cristianonicolai** [comment]
@paulovmr not sure if I'm missing some dependency but I got the following error when trying to run the showcase: 
JavaScriptException: (InvalidCharacterError) : Failed to execute 'add' on 'DOMTokenList': The token provided ('pficon pficon-blueprint') contains HTML space characters, which are not valid in tokens.
org.jbpm.workbench.jBPMShowcase-0.js:174522 Error: Failed to execute 'add' on 'DOMTokenList': The token provided ('pficon pficon-blueprint') contains HTML space characters, which are not valid in tokens.

**Comment by paulovmr** [comment]
@cristianonicolai You have to build the kie-wb-common associated PR for this to work.

**Comment by cristianonicolai** [comment]
@paulovmr thanks, that fixed :)

**Pull request merged**
