### PR TITLE
JBPM-5767 and JBPM-5894 - Migrate example case project to playground

### PR DESCRIPTION
**Pull request by cristianonicolai**
Remove reference to upstream gihub project
Use playground module for provisioning example project into kie server instance
Updated showcase installation docs
Removed authentication using single user to connect with Kie Server
Use library service to install and build itorders project

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@bsremac when you have a chance, cherry picking into 7.0.x branch.

**Comment by bsremac** [comment]
@cristianonicolai I have problems building _kie-wb-distributions_, after successfully building Casey from this PR.
The error I keep getting is:
```java
[INFO] 
[INFO] --- gwt-maven-plugin:2.8.0:compile (gwt-compile) @ kie-wb-webapp ---
[INFO] Loading inherited module 'org.kie.workbench.FastCompiledKIEWebapp'
[INFO]    Loading inherited module 'org.kie.workbench.KIEWebapp'
[INFO]       [ERROR] Line 155: Property 'errai.i18n.default_per_key' not found
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] KIE Workbench - Distributions ...................... SUCCESS [  1.770 s]
[INFO] KIE Theme .......................................... SUCCESS [  0.105 s]
[INFO] KIE Theme - Community .............................. SUCCESS [  0.850 s]
[INFO] KIE Theme - Product ................................ SUCCESS [  0.707 s]
[INFO] KIE Workbench Parent ............................... SUCCESS [  0.085 s]
[INFO] KIE Workbench - Home Page - Community .............. SUCCESS [  2.227 s]
[INFO] KIE Workbench - Webapp ............................. FAILURE [ 32.349 s]
[INFO] KIE Workbench - Distribution Wars .................. SKIPPED
[INFO] KIE Drools Workbench Parent ........................ SKIPPED
[INFO] KIE Drools Workbench - Home Page - Community ....... SKIPPED
[INFO] KIE Drools Workbench - Webapp ...................... SKIPPED
[INFO] KIE Drools Workbench - Distribution Wars ........... SKIPPED
[INFO] KIE Tomcat integration ............................. SKIPPED
[INFO] KIE (Drools) Workbench Tests :: Parent ............. SKIPPED
[INFO] KIE (Drools) Workbench Tests :: REST API ........... SKIPPED
[INFO] KIE (Drools) Workbench Tests :: GUI ................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 39.994 s
[INFO] Finished at: 2017-04-24T17:51:03+02:00
[INFO] Final Memory: 403M/1639M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:gwt-maven-plugin:2.8.0:compile (gwt-compile) on project kie-wb-webapp: Command failed with status 1 -> [Help 1]

```

**Comment by manstis** [comment]
Needs errai built locally (or latest SNAPSHOT available/built)

**Comment by nmirasch** [comment]
Building errai locally, it worked for me .

**Pull request merged**
