### PR TITLE
[7.3.x] GUVNOR-3129: Reconcile Pipeline definition API

### PR DESCRIPTION
**Pull request by wmedvede**
(cherry picked from commit 34e4b3dde76ac2205f26ce7c978846e8a8eb9b43)

### CODE REVIEW

**Comment by wmedvede** [comment]
Hi @porcelli would you mind reivew this PR?
Thanks.

Depends on:
https://github.com/kiegroup/guvnor/pull/524
https://github.com/kiegroup/kie-wb-common/pull/1207

**Comment by wmedvede** [comment]
10:16:10 Cleaning-up directory /home/jenkins/workspace/jbpm-wb-pullrequests-7.3.x/upstream-repos
10:16:28 Unexpected error while executing the Upstream repositories builder for PR builds! Failed to get open PRs for kiegroup/jbpm-designer
10:16:28 java.lang.RuntimeException: Failed to get open PRs for kiegroup/jbpm-designer
10:16:28 	at org.kie.jenkinsci.plugins.kieprbuildshelper.GitHubUtils.getOpenPullRequests(GitHubUtils.java:46)


10:16:28 Caused by: java.net.SocketTimeoutException: Read timed out
10:16:28 	at sun.reflect.GeneratedConstructorAccessor1431.newInstance(Unknown Source)
10:16:28 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
1

**Comment by wmedvede** [comment]
let's give it a second chance
jenkins retest this

**Comment by cristianonicolai** [comment]
@wmedvede 7.3.x branch is now closed, is this critical for pushing into 7.4.x?

**Pull request closed without merging**
