### PR TITLE
BXSMPROD-685: upgrade of weld to 3.x

### PR DESCRIPTION
**Pull request by mareknovotny**
https://issues.redhat.com/browse/BXMSPROD-685

Parent  PR https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1320

### CODE REVIEW

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
Jenkins retest this

**Comment by mareknovotny** [comment]
Jenkins retest this

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Review by yesamer — APPROVED** [review]

**Pull request merged**
