### PR TITLE
RHPAM-1957 Task List Saved Filters different expression when defining…

### PR DESCRIPTION
**Pull request by bxf12315**
… and using

@nmirasch Please review it.

### CODE REVIEW

**Comment by nmirasch** [comment]
@bxf12315 there is a PR (https://github.com/kiegroup/jbpm-wb/pull/1328) pending to merge that modify a bit this behaviour, could you give some time to merge that an see if this code still makes sense. The idea is not to clean the basic filters to allow the multiselect values reflecting the actives filters.

**Comment by bxf12315** [comment]
> @bxf12315 there is a PR (#1328) pending to merge that modify a bit this behaviour, could you give some time to merge that an see if this code still makes sense. The idea is not to clean the basic filters to allow the multiselect values reflecting the actives filters.

ok

**Comment by bxf12315** [comment]
I think the issue fixed by PR(https://github.com/kiegroup/jbpm-wb/pull/1328), So I am going to close it.

**Comment by cristianonicolai** [comment]
@bxf12315 can this PR be closed?

**Comment by bxf12315** [comment]
@cristianonicolai ok.

**Pull request closed without merging**
