### PR TITLE
 JBPM-6867, JBPM-6886, JBPM-6825, JBPM-6841, JBPM-6826, JBPM-6802 ,JBPM-6659, JBPM-6660 -  Runtime views update, new Manage section

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by bsremac** [comment]
@cristianonicolai I have tried out the builds,_kie-wb_ and _kie-server_ together, coming out of full downstream build. Well, they are useless. This is what I'm seeing (this is not what I was getting when building kie-wb locally)
screenshot from 2018-03-15 00-23-05

screenshot from 2018-03-15 00-22-43

**Comment by cristianonicolai** [comment]
@bsremac ok, good to know, I also got the same issue... still investigating

**Comment by cristianonicolai** [comment]
@bsremac just verified master without this change and the problem is already there.

**Comment by cristianonicolai** [comment]
Reverting the blocking changes for now
https://github.com/kiegroup/appformer/pull/238

**Comment by nmirasch** [comment]
@cristianonicolai @bsremac after the revert, it worked fine for me. (WF11)

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Pull request merged**
