### PR TITLE
DROOLS-1608 - move processes related classes from drools to jbpm

### PR DESCRIPTION
**Pull request by tsurdilo**

### CODE REVIEW

**Comment by tsurdilo** [comment]
@mswiderski just small update to default case def wid

**Comment by tsurdilo** [comment]
jBPM Workbench - Showcase module failing to compile due to issue not related to this change.

**Comment by mswiderski** [comment]
jenkins retest this

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
Jenkins retest please

**Pull request merged**
