### PR TITLE
[7.7.x] RHPAM-850: Fix Form Generation issues when using unsupported types 

### PR DESCRIPTION
**Pull request by pefernan**
Copy of https://github.com/kiegroup/jbpm-wb/pull/1100

@kkufova @cristianonicolai  could you please review?

This PR si part of an ensemble, merge with:
https://github.com/kiegroup/kie-wb-common/pull/1711
https://github.com/kiegroup/jbpm-wb/pull/1101

### CODE REVIEW

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by pszubiak** [comment]
Jenkins execute full downstream build

**Comment by pszubiak** [comment]
@pefernan Sorry I didn't noticed that you already requested full build.

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
@cristianonicolai two greens at last! are we still on time to merge?

**Pull request merged**
