### PR TITLE
[Rebase] RHPAM-1700 Column sorting is not retained after filters are applied i…

### PR DESCRIPTION
**Pull request by nmirasch**
…n task inbox business central

### CODE REVIEW

**Comment by nmirasch** [comment]
@cristianonicolai @bxf12315 This PR is the rebase required to https://github.com/kiegroup/jbpm-wb/pull/1277.
And needs this https://github.com/kiegroup/appformer/pull/613 merged
Reading the comments it seems all the comments are solved and it works fine, just to be able to merge before release just in case is needed.
Hope this helps.

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by bxf12315** [comment]
@nmirasch It is ok for me.

**Comment by nmirasch** [comment]
@cristianonicolai @bxf12315 regarding the original PR have been rebase this PR doesn't make sense. I want to close this one and leave the original threat to follow the  whole history. 
Is this ok?
Thanks all!

**Comment by bxf12315** [comment]
@nmirasch I was rebase my PR. So It's ok for me.
Thanks

**Comment by nmirasch** [comment]
@bxf12315 oooks, Done! :)

**Pull request closed without merging**
