### PR TITLE
[7.67.x] jbpm-designer dependecies removal

### PR DESCRIPTION
**Pull request by Ginxo**
**referenced Pull Requests**: 

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2058
* https://github.com/kiegroup/jbpm-wb/pull/1562

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by Ginxo** [comment]
Jenkins retest this

**Comment by lampajr** [comment]
It seems there are still references on the code using classes from `jbpm-designer-api`:
```
2022-08-30T06:52:15.8993464Z [ERROR] /home/runner/work/jbpm-wb/jbpm-wb/kiegroup_jbpm_wb/jbpm-wb-integration/jbpm-wb-integration-backend/src/main/java/org/jbpm/workbench/wi/backend/server/dd/DDConfigUpdater.java:[80,56] cannot find symbol
2022-08-30T06:52:15.8996019Z [ERROR]   symbol:   class DesignerWorkitemInstalledEvent
2022-08-30T06:52:15.8998781Z [ERROR]   location: class org.jbpm.workbench.wi.backend.server.dd.DDConfigUpdater
```

**Review by lampajr — APPROVED** [review]

**Review by inodeman — APPROVED** [review]
Looks good as far as I can tell

**Comment by LuboTerifaj** [comment]
I am testing the changes.

**Review by LuboTerifaj — COMMENTED** [review]
I didn't find any issues in the latest snapshot.

QE will also check the upcoming nightly builds on qe-jenkins.

**Pull request merged**
