### PR TITLE
JBPM-9044: upgrade to WF18

### PR DESCRIPTION
**Pull request by mareknovotny**
https://issues.redhat.com/browse/JBPM-9044

Parent PR kiegroup/droolsjbpm-build-bootstrap/pull/1203

### CODE REVIEW

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
so the failing test is somehow insisting on the old name of jbpm-wb-case-mgmt-showcase war.
Locally for me it works, but I could see the GAV of war is not strictly defined from pom.xml.

```
Unable to collect/resolve dependency tree for a resolution due to: Could not find artifact org.jbpm:jbpm-wb-case-mgmt-showcase:war:wildfly14:7.36.0-SNAPSHOT, caused by: Could not find artifact org.jbpm:jbpm-wb-case-mgmt-showcase:war:wildfly14:7.36.0-SNAPSHOT
```

**Comment by mareknovotny** [comment]
@cristianonicolai could you help me with finding what's wrong in the CI IT `org.jbpm.workbench.DeploymentIT.testCaseManagementDeployment` where the GAV is not correctly updated? It still tries to pull down wildfly14 instead of wildfly18 even locally it works. I suspect it is trying to download the latest available GAV from remote repository instead of local built one.

**Comment by cristianonicolai** [comment]
@mareknovotny it needs to be updated here https://github.com/kiegroup/jbpm-wb/blob/master/jbpm-wb-integration/jbpm-wb-integration-backend/src/main/resources/casemgmt.properties#L1

**Comment by mareknovotny** [comment]
ok, I got it now, it was missed updated in https://github.com/kiegroup/jbpm-wb/blob/master/jbpm-wb-integration/jbpm-wb-integration-backend/src/main/resources/casemgmt.properties#L1 :)

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Pull request merged**
