### PR TITLE
GUVNOR-3023: Support provisioning of KIE Server instances by Guvnor ALA

### PR DESCRIPTION
**Pull request by errantepiphany**
GUVNOR-3023: Support provisioning of KIE Server instances by Guvnor ALA
https://issues.jboss.org/browse/GUVNOR-3023

### CODE REVIEW

**Comment by cristianonicolai** [comment]
ok to test

**Comment by errantepiphany** [comment]
This won't pass until the other PRs associated with the jira are processed:
https://issues.jboss.org/browse/GUVNOR-3023

**Comment by cristianonicolai** [comment]
@errantepiphany seems like the same fix you applied for this PR https://github.com/kiegroup/guvnor/pull/477 needs to be done in here to avoid the duplicated classes issue.

**Comment by errantepiphany** [comment]
@cristianonicolai : Moved the fix to droolsjbpm-build-bootstrap. Re-pushed, and now waiting for the automated builds to run again.

**Comment by errantepiphany** [comment]
@cristianonicolai : Perhaps this won't pass until the PR in droolsjbpm-build-bootstrap gets processed?

**Comment by cristianonicolai** [comment]
@errantepiphany as you have all PR's with the same branch name they actually get build together in Jenkins. I would expect this one to pass now.

**Comment by errantepiphany** [comment]
@cristianonicolai Cool thanks. :)

**Comment by errantepiphany** [comment]
Replacing with new PR against 7.2.x.

**Pull request closed without merging**
