### PR TITLE
[7.7.x] RHPAM-1299: Recover standalone perspectives for process / task forms

### PR DESCRIPTION
**Pull request by pefernan**
I had to add them back do to an escalation from a customer...

@jsoltes @cristianonicolai could you please review?

### CODE REVIEW

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by jsoltes** [comment]
@cristianonicolai you did not give me a chance to review...

**Comment by cristianonicolai** [comment]
@jsoltes really sorry, I usually wait for all the requested reviews but acted too soon on this one.

**Comment by jsoltes** [comment]
@cristianonicolai np., just don't forget about me next time.

**Pull request merged**
