### PR TITLE
JBPM-5769 - Allow showcase app context to be the same the deployed wa…

### PR DESCRIPTION
**Pull request by cristianonicolai**
…r file name

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@krisv as discussed.

**Comment by krisv** [comment]
+1

**Comment by bsremac** [comment]
@cristianonicolai I can't figure it out from the changes whether this mean that Showcase App context is now configurable on Wildfly's start-up or the context is hard-coded to to whatever is the name of the Showcase App .war file.
The latter one works as expected, just not sure about the context configuration options.

**Comment by cristianonicolai** [comment]
@bsremac exactly, this change only means that now the context should be the same as the final .war file name. There is no specific configuration for it on Wildfly.

**Pull request merged**
