### PR TITLE
GUVNOR-3128: Store Guvnor ALA state using VFS (#822)

### PR DESCRIPTION
**Pull request by wmedvede**
(cherry picked from commit 1643dc300a0a52c4095e8e15a89407be4e62f669)

### CODE REVIEW

**Comment by wmedvede** [comment]
@porcelli This is the peer PR for the already merged into 7.2.x branch:
    https://github.com/kiegroup/jbpm-wb/pull/822

Would you mind review?
Thanks

depends on:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/498
https://github.com/kiegroup/guvnor/pull/489
https://github.com/kiegroup/kie-wb-common/pull/1022

**Comment by porcelli** [comment]
This is failing: 
https://github.com/kiegroup/jbpm-wb/blob/master/jbpm-wb-integration/jbpm-wb-integration-backend/src/test/java/org/jbpm/workbench/wi/backend/server/casemgmt/service/CaseProvisioningIT.java#L60

**Comment by wmedvede** [comment]
hard to detect this "org.guvnor:guvnor-ala-registry-local" constant, will look

**Comment by wmedvede** [comment]
fixed

**Comment by wmedvede** [comment]
jenkins retest this

**Comment by wmedvede** [comment]
this is the error right now

19:05:03 [ERROR] [ERROR] Some problems were encountered while processing the POMs:
19:05:03 [WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.sun.xml.bind:jaxb-impl:jar -> duplicate declaration of version (?) @ org.kie:kie-spring:[unknown-version], /home/jenkins/workspace/jbpm-wb-downstream-pullrequests/upstream-repos/droolsjbpm-integration/kie-spring/pom.xml, line 283, column 17
19:05:03 [ERROR] 'dependencies.dependency.version' for org.kie.server:kie-server-controller-websocket:jar is missing. @ org.kie.server:kie-server-controller-standalone:[unknown-version], /home/jenkins/workspace/jbpm-wb-downstream-pullrequests/upstream-repos/droolsjbpm-integration/kie-server-parent/kie-server-controller/kie-server-controller-standalone/pom.xml, line 25, column 17
19:05:03 [ERROR] 'dependencies.dependency.version' for org.kie.server:kie-server-controller-websocket-common:jar is missing. @ org.kie.server:kie-server-controller-standalone:[unknown-version], /home/jenkins/workspace/jbpm-wb-downstream-pullrequests/upstream-repos/droolsjbpm-integration/kie-server-parent/kie-server-controller/kie-server-controller-standalone/pom.xml, line 29, column 17
19:05:03 [ERROR] 'dependencies.dependency.version' for org.kie.server:kie-server-controller-websocket-common:jar is missing. @ org.kie.server:kie-server-controller-websocket:[unknown-version], /home/jenkins/workspace/jbpm-wb-downstream-pullrequests/upstream-repos/droolsjbpm-integration/kie-server-parent/kie-server-controller/kie-server-controller-websocket/pom.xml, line 39, column 17
19:05:03 [ERROR] 'dependencies.dependency.version' for org.jboss.spec.javax.websocket:jboss-websocket-api_1.0_spec:jar is missing. @ org.kie.server:kie-server-controller-websocket:[unknown-version], /home/jenkins/workspace/jbpm-wb-downstream-pullrequests/upstream-repos/droolsjbpm-integration/kie-server-parent/kie-server-controller/kie-server-controller-websocket/pom.xml, line 75, column 17
19:05:03 [ERROR] 'dependencies.dependency.version' for org.kie.server:kie-server-controller-websocket-common:jar is missing. @ or

19:05:03 [ERROR] 'dependencies.dependency.version' for org.kie.server:kie-server-controller-websocket-client:jar is missing. @ org.kie.server:kie-server-integ-tests-controller:[unknown-version], /home/jenkins/workspace/jbpm-wb-downstream-pullrequests/upstream-repos/droolsjbpm-integration/kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/pom.xml, line 103, column 17
19:05:03 [ERROR] 'dependencies.dependency.version' for org.kie.server:kie-server-controller-websocket-common:jar is missing. @ org.kie.server:kie-server-integ-tests-controller:[unknown-version], /home/jenkins/workspace/jbpm-wb-downstream-pullrequests/upstream-repos/droolsjbpm-integration/kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/pom.xml, line 108, column 17
19:05:03 
19:05:03 	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:422)
19:05:03 	at org.apache.maven.graph.DefaultGraphBuilder.collectProjects(DefaultGraphBuilder.java:419)
19:05:03 	at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor(DefaultGraphBuilder.java:410)
19:05:03 	at org.apache.maven.graph.DefaultGraphBuilder.build(DefaultGraphBuilder.java:83)
19:05:03 	at org.apache.maven.DefaultMaven.buildGraph(DefaultMaven.java:491)
19:05:03 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:219)
19:05:03 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
19:05:03 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
19:05:03 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
19:05:03 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
19:05:03 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)

**Comment by wmedvede** [comment]
jenkins retest this

**Comment by psiroky** [comment]
@wmedvede are you sure the issue got fixed? Blindly retesting the PR won't make any difference if the issue is somewhere else.

**Comment by wmedvede** [comment]
@psiroky I've fixed the issue of course related with this project. But unfortunately I don't have the time to fix all the tests that eventually fails in other product areas that I even have no idea about. Wish I had the time to do it, but unfortunately I don't have this time right now. Specially when form time to time to time there are tests that fails in a random basis.
Anyway, this PR right now will never got the green flags since a PR that should come after this one, was merged in the middle and now all the PRs related to this one will of course fail.
So the only way now is to rebase all the PRs related to this with master and push again.

**Comment by psiroky** [comment]
@wmedvede I am not saying you need to go fix all other tests. I am just saying that blindly re-testing PRs without any change somewhere will usually not make it the build green. Considering the error above, it is a Maven error, not a test error. Looking at the "master" build should give you an idea if the error is also there, or only on your PR. If the error is the same for the "master" build, then it is very likely someone needs to fix it there re-testing the PR.

**Comment by wmedvede** [comment]
@psiroky , I know what you say, but believe it or not there are tests that also fails in a random basis.
see this thread

https://github.com/kiegroup/kie-wb-common/pull/1026

the build of this PR failed the 3 first times due to random failing tests.

**Comment by psiroky** [comment]
@wmedvede I know very well there are randomly failing tests. And I am spending a lot of time trying to fix at least some of them. Unfortunately, I can't really fix everything myself. Everyone needs to pitch in.

**Comment by wmedvede** [comment]
@psiroky I know for sure you are spending time on trying to fix this, and with high probability there are times when you can't dedicate more time to "pitch in" on this tests. I know what this is. 
But since some of this tests are very well identified, likely a good way to treat them is as simple as the "owner" of this test fix them. This could be let's say reasonable approach. Anyway this is something that likely neither you nor me can manage.

**Pull request merged**
