### PR TITLE
JBPM-8306: Process diagram images are hardcoded to large sizes

### PR DESCRIPTION
**Pull request by nmirasch**
work with svg viewBox attribute instead with and height

### CODE REVIEW

**Comment by nmirasch** [comment]
depends on https://github.com/kiegroup/droolsjbpm-integration/pull/1767

**Comment by nmirasch** [comment]
@cristianonicolai @jstastny-cz Updated the way to retrieve the svg  width and height from viewbox attribute. Doing it we allow to see the process diagram in the same scale that was created. Let me know what you think. Thanks!

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by jstastny-cz** [comment]
@nmirasch why exactly do we need to set the width and height attributes while we have the viewBox?

**Comment by nmirasch** [comment]
@jstastny-cz it is done to keep working the zooming on the diagram that use this values to move the svg to the top- left corner. I thought this was the faster way to avoid redo the zooming regarding the new svg attributes

**Comment by cristianonicolai** [comment]
@jstastny-cz are you happy with these changes?

**Comment by jstastny-cz** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox
> The value of the viewBox attribute is a list of four numbers min-x, min-y, width and height, separated by whitespace and/or a comma,

The attribute value with commas should be probably considered valid and should be handled accordingly. @nmirasch what do you think?

**Comment by nmirasch** [comment]
@jstastny-cz regarding this viewbox attribute is added at rest service and processed here, I don't see the possible case that the viewbox comes separated by comma
@cristianonicolai do you think that is useful to consider that case here?

**Comment by cristianonicolai** [comment]
@nmirasch agree with you, we're consuming the image only from the specific endpoint that we manage, knowing specifically how it would be formatted/set values.

**Comment by nmirasch** [comment]
@cristianonicolai Ok, Thanks,  and thank you @jstastny-cz for bring this up

**Comment by nmirasch** [comment]
rebased

**Pull request merged**
