### PR TITLE
JBPM-7864 - Allow extra space between page selector and bottom of the…

### PR DESCRIPTION
**Pull request by cristianonicolai**
… page.

### CODE REVIEW

**Comment by cristianonicolai** [comment]
Assembly:
- https://github.com/kiegroup/jbpm-wb/pull/1218
- https://github.com/kiegroup/appformer/pull/499

**Comment by bsremac** [comment]
@cristianonicolai Ain't working for me after building the _kie-wb_ off of the PRs. The pager options stay put, but they really stay put :)
Take a look at the attached screencast.
[Screencast from 18-10-18 13:58:47.zip](https://github.com/kiegroup/jbpm-wb/files/2491766/Screencast.from.18-10-18.13.58.47.zip)

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by cristianonicolai** [comment]
@bsremac definitely not what I was expecting, let me try out the jbpm-server-full when it builds out.

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Pull request merged**
