### PR TITLE
[7.26.x] JBPM-8774: Task List Bulk Reassign error when a task has inappropriat…

### PR DESCRIPTION
**Pull request by nmirasch**
…e status (#1389)

### CODE REVIEW

**Comment by nmirasch** [comment]
@cristianonicolai @jstastny-cz  cherry-picking to 7.26.x branch.

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by nmirasch** [comment]
Jenkins execute full downstream build

**Comment by nmirasch** [comment]
Jenkins execute full downstream build

**Pull request closed without merging**
