### PR TITLE
JBPM-9927 GWT:run broken in jbpm-wb

### PR DESCRIPTION
**Pull request by bxf12315**
**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[https://issues.redhat.com/browse/JBPM-9927](JBPM-9927)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by Rikkola — APPROVED** [review]
Thank you. I will need to move the -showcases to use file system realm, but this helps a lot before I have time to do that.

**Comment by mareknovotny** [comment]
please check the GHA runs, there are 2 test failures on both jdks

**Review by nmirasch — APPROVED** [review]
jbpm-wb-showcase works fine now, I'm just guessing if we need to apply similar changes on jbpm-wb-case-mgmt-showcase

**Comment by mareknovotny** [comment]
jenkins retest this please.

Jenkins CI job failed on memory problem with GWT compiling error 143

**Comment by mareknovotny** [comment]
GHA resulted in 
`jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/src/test/java/org/jbpm/workbench/cm/DeploymentIT.java:125 | org.kie.server.api.exception.KieServicesHttpException: Unexpected HTTP response code when requesting URI 'http://127.0.0.1:8080/kie-server/services/rest/server'! Error code: 401, message: <html><head><title>Error</title></head><body>Unauthorized</body></html>`

**Comment by bxf12315** [comment]
> GHA resulted in `jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/src/test/java/org/jbpm/workbench/cm/DeploymentIT.java:125 | org.kie.server.api.exception.KieServicesHttpException: Unexpected HTTP response code when requesting URI 'http://127.0.0.1:8080/kie-server/services/rest/server'! Error code: 401, message: <html><head><title>Error</title></head><body>Unauthorized</body></html>`

I find the IT pass in jenkins log,  I will try to build it.

**Comment by bxf12315** [comment]
jenkins retest this please.

**Comment by bxf12315** [comment]
> jbpm-wb-showcase works fine now, I'm just guessing if we need to apply similar changes on jbpm-wb-case-mgmt-showcase

yes, If the PR passed, I will raise another PR to fix it in jbpm-wb-case-mgmt-showcase

**Comment by bxf12315** [comment]
jenkins retest this please.

**Comment by RishiRajAnand** [comment]
jenkins retest this please.

**Comment by RishiRajAnand** [comment]
@bxf12315  could you please check the failing tests ?

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by bxf12315** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
@bxf12315 you probably see much better CI results if you rebase this old PR

**Comment by bxf12315** [comment]
ok I w

> @bxf12315 you probably see much better CI results if you rebase this old PR

ok

**Comment by mareknovotny** [comment]
Isn't this failure related i think so?

```
[org.jbpm.workbench.DeploymentIT.testCustomQueriesDeployedToKieServer](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/pullrequest/job/jbpm-wb-main.pr/90/testReport/org.jbpm.workbench/DeploymentIT/testCustomQueriesDeployedToKieServer/)

 Error Details
Server that this client is connected to has no capabilities to handle QueryServicesClient

 Stack Trace
org.kie.server.api.exception.KieServicesException: Server that this client is connected to has no capabilities to handle QueryServicesClient
	at org.jbpm.workbench.DeploymentIT.testCustomQueriesDeployedToKieServer(DeploymentIT.java:137)
```

**Comment by bxf12315** [comment]
> Isn't this failure related i think so?
> 
> ```
> [org.jbpm.workbench.DeploymentIT.testCustomQueriesDeployedToKieServer](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/pullrequest/job/jbpm-wb-main.pr/90/testReport/org.jbpm.workbench/DeploymentIT/testCustomQueriesDeployedToKieServer/)
> 
>  Error Details
> Server that this client is connected to has no capabilities to handle QueryServicesClient
> 
>  Stack Trace
> org.kie.server.api.exception.KieServicesException: Server that this client is connected to has no capabilities to handle QueryServicesClient
> 	at org.jbpm.workbench.DeploymentIT.testCustomQueriesDeployedToKieServer(DeploymentIT.java:137)
> ```

the commit is just my draft code, I think it does not work. I will continue to investigate.

**Pull request closed without merging**
