### PR TITLE
JBPM-6785: redraw table to show empty widget

### PR DESCRIPTION
**Pull request by michpetrov**
Issue: [JBPM-6785](https://issues.jboss.org/browse/JBPM-6785)

### CODE REVIEW

**Comment by michpetrov** [comment]
ok someone might want to rein in the bot :)

**Comment by cristianonicolai** [comment]
ok to test

**Comment by cristianonicolai** [comment]
@michpetrov could you add a test for this fix please?

**Comment by michpetrov** [comment]
Ah ok, I'll do that.

**Comment by cristianonicolai** [comment]
@michpetrov don't you need to call _show_ first so _redrawParametersGrid_ is set to true? In this case, I think it still false.
You can probably skip creating the mock for the event as is never used, I would simply pass _null_.

**Comment by michpetrov** [comment]
@cristianonicolai well, that took a lot of trial and error but I think I got it now

**Comment by cristianonicolai** [comment]
@michpetrov you did great to sort all necessary mocks, I guess this is because of what is done under the _show_ method. In situations like this, what I tend to do is to isolate te logic needed for the test. For example, you could create another method to set _redrawParametersGrid_ that is called from the _show_ method. This way, for testing, you can simply call that new method.

**Comment by bsremac** [comment]
I'm having troubles compiling the _jbpm-wb_ off this PR.
In particular, _jBPM Workbench - Showcase_ is failing with the errors such as:
```
Tracing compile failure path for type 'org.kie.workbench.common.screens.javaeditor.client.editor.JavaEditorPresenter'
[INFO]       [ERROR] Errors in 'jar:file:/home/bsremac/.m2/repository/org/kie/workbench/screens/kie-wb-common-java-editor-client/7.8.0-SNAPSHOT/kie-wb-common-java-editor-client-7.8.0-SNAPSHOT-sources.jar!/org/kie/workbench/common/screens/javaeditor/client/editor/JavaEditorPresenter.java'
[INFO]          [ERROR] Line 97: The method onValidate() of type JavaEditorPresenter must override or implement a supertype method
[INFO]       [ERROR] Errors in 'jar:file:/home/bsremac/.m2/repository/org/kie/workbench/widgets/kie-wb-metadata-widget/7.8.0-SNAPSHOT/kie-wb-metadata-widget-7.8.0-SNAPSHOT-sources.jar!/org/kie/workbench/common/widgets/metadata/client/KieEditor.java'
```

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
@bsremac is this PR working for you now?

**Pull request merged**
