### PR TITLE
JBPM-7003 - Update page size selector style to match PatternFly dropdown

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
Set of PRs to be merged together:
- https://github.com/kiegroup/kie-wb-distributions/pull/715
- https://github.com/kiegroup/jbpm-wb/pull/1010
- https://github.com/kiegroup/kie-wb-common/pull/1534
- https://github.com/kiegroup/appformer/pull/257

**Comment by pefernan** [comment]
@bsremac  Hi it seems that the appformer PR has been been merged and the build is broken.Are the other PRs ready to merge?

**Comment by bsremac** [comment]
@pefernan I have been trying to build the whole solution locally for two days now.
Yesterday I finally managed to get _kie-wb-common_ piece compiled. I will give it one more go this morning to build _jbpm-wb_ piece and then _kie-wb-distributions_ and check out how it looks from the UI.

**Comment by pefernan** [comment]
@bsremac Ok, let me know if you need my help. This is blocking one of my PR's and I really need this to be merged.

**Pull request merged**
