### PR TITLE
Revert "JBPM-8206 - Add Task Name and Process Id quick filters with domain co…"

### PR DESCRIPTION
**Pull request by cristianonicolai**
Reverts kiegroup/jbpm-wb#1289

### CODE REVIEW

**Comment by cristianonicolai** [comment]
Fix for failing tests should be in https://github.com/kiegroup/appformer/pull/639

**Comment by nmirasch** [comment]
Jenkins execute full downstream build

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
Opened a new PR for 7.18.x branch: https://github.com/kiegroup/jbpm-wb/pull/1296

**Pull request closed without merging**
