### PR TITLE
JBPM-7810 - Remove portable annotation from client only events

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by bsremac** [comment]
@cristianonicolai I still see the error after building _kie-wb_ off of this PR.

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by nmirasch** [comment]
@cristianonicolai, @bsremac it worked fine for me

**Comment by bsremac** [comment]
@cristianonicolai @nmirasch I must have been using some rouge build the first time. It's working fine for me as well when using the build produced by the full downstream build.

**Pull request merged**
