### PR TITLE
RHBA-578 & JBPM-6886 PrimaryActionMenu updated

### PR DESCRIPTION
**Pull request by nmirasch**

### CODE REVIEW

**Comment by nmirasch** [comment]
@cristianonicolai  @bsremac Updated the PrimaryActionMenuBuilder. Could you take a look?
I have included two commits, covering both issues. Do you think that makes sense squash them?
any thought is, as always very welcome. Thanks!

**Comment by cristianonicolai** [comment]
@nmirasch I think squashing both commits is fine, that is what is going to happen anyway when we merge into master. 
My only comment is that you could reuse the isEnabled/setEnabled and addEnabledStateChangeListener methods from the MenuItem API to toggle those buttons. That way you avoid having to keep a reference to the menu builder too.

**Comment by bsremac** [comment]
@nmirasch Looks good.
@nmirasch @cristianonicolai Have one question regarding the text inside the button which opens up the dialog for starting new process instance.
In Process Instances perspective the text inside the button is _New Process Instance_ and in Process Defintions Details Panel the button with the same action has text _New Instance_ .
How about aligning these two? I have no preference regarding the text itself as long as it is the same in both places.

**Comment by cristianonicolai** [comment]
@bsremac +1 for _New Process Instance_

**Comment by nmirasch** [comment]
@cristianonicolai  @bsremac changed the button text and done a bit refactor on PrimaryActionMenuBuilder to work with listeners and avoid to have the actions references for that purpose.
@cristianonicolai I didn't find the way to that setEnabled notify the listeners via API but added there the methods just in case. Could you take a look? 
Thanks!

**Comment by bsremac** [comment]
+1

**Pull request merged**
