### PR TITLE
[7.67.x] [JBPM-10100] [GSS] (7.12.0) Select from PROCESSINSTANCELOG takes too long

### PR DESCRIPTION
**Pull request by elguardian**
Jira: https://issues.redhat.com/browse/JBPM-10100

### CODE REVIEW

**Comment by elguardian** [comment]
Jenkins retest this please

**Comment by elguardian** [comment]
Jenkins retest this please

**Comment by elguardian** [comment]
Jenkins retest this please

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by elguardian** [comment]
Jenkins retest this please

**Comment by elguardian** [comment]
Jenkins retest this please

**Comment by elguardian** [comment]
Jenkins retest this please

**Pull request merged**
