### PR TITLE
[7.18.x] RHPAM-1700 Column sorting is not retained after filters are applied i…

### PR DESCRIPTION
**Pull request by bxf12315**
…n task inbox business central

@cristianonicolai backport to 7.18.x

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@bxf12315 please link dependent pr

**Comment by bxf12315** [comment]
The PR dependent on https://github.com/kiegroup/appformer/pull/652

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by cristianonicolai** [comment]
@jstastny-cz can you please review this PR, thanks.

**Comment by cristianonicolai** [comment]
@ederign can you please merge this and https://github.com/kiegroup/appformer/pull/652 together, thanks

**Pull request merged**
