### PR TITLE
[7.52.x] RHPAM-3496 - Custom task thumbnails are not consistent

### PR DESCRIPTION
**Pull request by Josephblt**
All icons are synchronized across projects. Equal sizes, images and naming pattern.

**JIRA**: [RHPAM-3496](https://issues.redhat.com/browse/RHPAM-3496)

**Referenced Pull Requests**:
https://github.com/kiegroup/jbpm/pull/1910
https://github.com/kiegroup/kie-wb-common/pull/3616

**All Pull Requests need to be merged for this fix to work.**

**Business Central**: [WAR file](https://drive.google.com/file/d/13VqTL9mMT9kkuK9qaQy0fo6errRO2UM5/view?usp=sharing)

### CODE REVIEW

**Comment by Josephblt** [comment]
Jenkins run fdb
Jenkins run cdb

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run fdb

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Comment by Josephblt** [comment]
@LuboTerifaj, please remember to use the .war provided in the description for testing as it contains the changes from the other PR's. The one in FDB won't work.

**Comment by Josephblt** [comment]
Jenkins run cdb
Jenkins run fdb

**Review by LuboTerifaj — APPROVED** [review]
Hello @Josephblt ,

I didn't find any more issues.

Thank you for the fix!

**Review by LuboTerifaj — CHANGES_REQUESTED** [review]
Hi @Josephblt , @romartin ,

note, the legacy designer doesn't work as expected (see https://github.com/kiegroup/jbpm-designer/pull/902#pullrequestreview-636928422 for more details).

Therefore I would recommend to postpone merging and retest it with correct changes or without changes at all for legacy designer.

Thanks!

**Comment by Josephblt** [comment]
Jenkins run cdb

**Review by LuboTerifaj — APPROVED** [review]
@Josephblt thanks for the update. It looks good to me now.

**Review by romartin — APPROVED** [review]

**Pull request merged**
