### PR TITLE
6.5.x allow custom marshalling strategies

### PR DESCRIPTION
**Pull request by ngs-mtech**
Enable change the target PlaceholderResolverStrategy this configuration helper configures while any persistence.xml file is modified.

### CODE REVIEW

**Comment by ngs-mtech** [comment]
Reported issue on:
jBPMJBPM-6082
DeploymentDescriptorConfigurationUpdater do not enable use of custom JPAPlacehoderStrategies

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser3** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser3** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by jsoltes** [comment]
@cristianonicolai is this still actual? or should we close it?

**Pull request closed without merging**
