### PR TITLE
RHPAM-850: Fix Form Generation issues when using unsupported types

### PR DESCRIPTION
**Pull request by pefernan**
@cristianonicolai @kkufova could you please review?

This is part of an ensemble, merge with:
https://github.com/kiegroup/kie-wb-common/pull/1709
https://github.com/kiegroup/jbpm-wb/pull/1100

@kkufova you can find a reproducer here: https://github.com/pefernan/RHPAM-850-form-generation-unsupported-types

### CODE REVIEW

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by cristianonicolai** [comment]
@pefernan overall looks good, just wondering if there could be any tests to help validate these changes.

**Comment by pefernan** [comment]
@cristianonicolai yes I'll be adding tests now, just sent the PR to let QE start testing it while I write tests

**Comment by pefernan** [comment]
@cristianonicolai you are so fast!

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by pefernan** [comment]
@cristianonicolai two greens at last! are we still on time to merge?

**Pull request merged**
