### PR TITLE
JBPM-9237 Invalid column name 'process_inst_id' or 'activity_id' due …

### PR DESCRIPTION
**Pull request by bxf12315**
…to case sensitivity on ms sql server

merge together with https://github.com/kiegroup/droolsjbpm-integration/pull/2157

### CODE REVIEW

**Comment by bxf12315** [comment]
> https://github.com/kiegroup/jbpm/blob/d5538b18f3e3f560f80d203dc517f138e6307279/jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/jpa/ExecutionErrorInfo.java#L70

yes, you are right, I just do not know what kind of impact this will have to do an already existing database?

**Comment by afalhambra** [comment]
> > https://github.com/kiegroup/jbpm/blob/d5538b18f3e3f560f80d203dc517f138e6307279/jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/jpa/ExecutionErrorInfo.java#L70
> 
> yes, you are right, I just do not know what kind of impact this will have to do an already existing database? So change query is a simple way. You can refer to kris's comment, I think it is right.

Yes, I see. But will the issue come up again if we skip that column? or it's only happening for the 2 queries you have modified?
I'm only concerned if we skip that change and issue raise again. What do you think?

**Comment by bxf12315** [comment]
> > > [kiegroup/jbpm@`d5538b1`/jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/jpa/ExecutionErrorInfo.java#L70](https://github.com/kiegroup/jbpm/blob/d5538b18f3e3f560f80d203dc517f138e6307279/jbpm-runtime-manager/src/main/java/org/jbpm/runtime/manager/impl/jpa/ExecutionErrorInfo.java#L70)
> > 
> > 
> > yes, you are right, I just do not know what kind of impact this will have to do an already existing database? So change query is a simple way. You can refer to kris's comment, I think it is right.
> 
> Yes, I see. But will the issue come up again if we skip that column? or it's only happening for the 2 queries you have modified?
> I'm only concerned if we skip that change and issue raise again. What do you think?

yes, the issue still exists, we need to do full type database test.

**Comment by afalhambra** [comment]
> yes, the issue still exists, we need to do full type database test

But issue would be resolved by fixing queries[1][2][3] in json file: 

https://github.com/kiegroup/jbpm-wb/blob/54fc4eb0babdd5cd66735e51c450de08557a700c/jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/main/resources/default-query-definitions.json

So I guess there is no need to change column "id" in table ExecutionErrorInfo to uppercase. I would say we're good with your PR as is right now, wdyt?


[1] https://github.com/kiegroup/jbpm-wb/blob/54fc4eb0babdd5cd66735e51c450de08557a700c/jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/main/resources/default-query-definitions.json#L5
[2] https://github.com/kiegroup/jbpm-wb/blob/54fc4eb0babdd5cd66735e51c450de08557a700c/jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/main/resources/default-query-definitions.json#L35
[3] https://github.com/kiegroup/jbpm-wb/blob/54fc4eb0babdd5cd66735e51c450de08557a700c/jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/main/resources/default-query-definitions.json#L53

**Comment by bxf12315** [comment]
> > yes, the issue still exists, we need to do full type database test
> 
> But issue would be resolved by fixing queries[1][2][3] in json file with the changes you are introducing in this PR:
> 
> [`54fc4eb`/jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/main/resources/default-query-definitions.json](https://github.com/kiegroup/jbpm-wb/blob/54fc4eb0babdd5cd66735e51c450de08557a700c/jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/main/resources/default-query-definitions.json)
> 
> So I guess there is no need to change column "id" in table ExecutionErrorInfo to uppercase. I would say we're good with your PR as is right now, wdyt?
> 
> [1]
> 
> https://github.com/kiegroup/jbpm-wb/blob/54fc4eb0babdd5cd66735e51c450de08557a700c/jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/main/resources/default-query-definitions.json#L5
> 
> 
> [2]
> https://github.com/kiegroup/jbpm-wb/blob/54fc4eb0babdd5cd66735e51c450de08557a700c/jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/main/resources/default-query-definitions.json#L35
> 
> 
> [3]
> https://github.com/kiegroup/jbpm-wb/blob/54fc4eb0babdd5cd66735e51c450de08557a700c/jbpm-wb-kie-server/jbpm-wb-kie-server-backend/src/main/resources/default-query-definitions.json#L53

[2] query is working fine on case sensitivity mssql, I test it, so do not change it.

**Comment by bxf12315** [comment]
@afalhambra Can we merge the issue?

**Comment by gmunozfe** [comment]
@bxf12315 backport it also to 7.39.x

**Pull request merged**
