### PR TITLE
JBPM-8391: Combined view of task comments and task work tabs. UX Styl…

### PR DESCRIPTION
**Pull request by nmirasch**
…ing fixes

### CODE REVIEW

**Comment by nmirasch** [comment]
@cristianonicolai @jstastny-cz  UX requested changes added, Could you take a look? Thanks

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by cristianonicolai** [comment]
@nmirasch not sure if expected but the comments section isnt using the full width available, see:

Selection_018

That is because _col-md-8_, instead if you use _col-md-12_ looks better to me, but not sure about UX comment on this. See:

image

**Comment by nmirasch** [comment]
@cristianonicolai yes, it looks as UX team expected https://issues.jboss.org/browse/BAPL-1255?focusedCommentId=13737153&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13737153

**Comment by nmirasch** [comment]
Jenkins execute full downstream build

**Pull request merged**
