### PR TITLE
GUVNOR-3023: Support provisioning of KIE Server instances by Guvnor ALA

### PR DESCRIPTION
**Pull request by errantepiphany**
GUVNOR-3023: Support provisioning of KIE Server instances by Guvnor ALA
https://issues.jboss.org/browse/GUVNOR-3023

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@errantepiphany you might still want to send a PR for master anyway. We need to keep master in sync with any new feature/fix.

**Comment by errantepiphany** [comment]
@cristianonicolai Just sent you an email with all 3 PRs for master, in addition to all 3 PRs for 7.2.x.

**Comment by cristianonicolai** [comment]
@errantepiphany to help the review and merge process it is a good practice to make a comment in the PR with the reference to any dependent PR. That way becomes easy for someone looking at merging if this is all good to go or not.

**Comment by errantepiphany** [comment]
@cristianonicolai Good to know, thanks. I'll do that from now on.

**Comment by errantepiphany** [comment]
PRs rebased against master. All these go together:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/489
https://github.com/kiegroup/guvnor/pull/485
https://github.com/kiegroup/jbpm-wb/pull/816

**Pull request merged**
