### PR TITLE
JBPM-8953 Load saved filter after Save filter launches an error

### PR DESCRIPTION
**Pull request by bxf12315**

### CODE REVIEW

**Comment by nmirasch** [comment]
Jenkins execute full downstream build

**Comment by cristianonicolai** [comment]
@jstastny-cz the logic on the iterator looks fine to me, hasNext will include the first item, unless I missing something here.

**Comment by jstastny-cz** [comment]
Correct, excuse my morning dementia.

**Comment by jstastny-cz** [comment]
Ready to be merged, even though full downstream reports failure, the business central war is available and the fix has been verified.

**Pull request merged**
