### PR TITLE
JBPM-9740 We also wanted to display 'Show instance badges' in process…

### PR DESCRIPTION
**Pull request by bxf12315**
… map in the SVG file which is returned by url /server/containers/{containerId}/images/processes/{processId}

**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[JBPM-9740](https://issues.redhat.com/browse/JBPM-9740)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* https://github.com/kiegroup/droolsjbpm-integration/pull/2484
* link 2
* link 3 etc.

<details>
The PR also can fix https://issues.redhat.com/browse/JBPM-9741.
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by prashuts** [comment]
Jenkins run fdb

**Comment by prashuts** [comment]
@bxf12315 FDB failed , can you please check

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by nmirasch** [comment]
@bxf12315 I think the JBPM-9741 commit should have it's own PR.

**Review by prashuts — APPROVED** [review]
LGTM

**Comment by bxf12315** [comment]
@nmirasch @prashuts 
I think it's not necessary after https://github.com/kiegroup/jbpm-wb/pull/1501. 
Now, I think we just need https://github.com/kiegroup/droolsjbpm-integration/pull/2484. Please check it.

**Comment by prashuts** [comment]
@bxf12315  Yes but the changes made in this PR which is not available in https://github.com/kiegroup/jbpm-wb/pull/1501 , will this be a problem . And i could not see these changes in master as well.
@nmirasch What do you suggest?

**Comment by bxf12315** [comment]
> @bxf12315 Yes but the changes made in this PR which is not available in #1501 , will this be a problem . And i could not see these changes in master as well.
> @nmirasch What do you suggest?

https://github.com/kiegroup/jbpm-wb/commit/52ee4679fb1d9d7772e9699b8f683245f1e18f81 ?

**Comment by prashuts** [comment]
@bxf12315  i meant file changes are different in both the PR's. If that's OK then no problem from my side

**Comment by nmirasch** [comment]
@bxf12315, @prashuts I see some changes contained in this PR that are related with by JBPM-9741, and that was the reason to create another PR with those changes related with the Diagram tab at BC. 
What I don't have clear here if the other changes incorporated here (ProcessDiagramWidgetViewImpl.java  and ProcessInstanceDiagramViewImpl) are needed to keep working as it was, even the kie-server  is showing an svg with the option to see the badges inside the same svg (https://github.com/kiegroup/droolsjbpm-integration/pull/2484).

My understanding was that we were going to change the svg served by the kie-server to include the badges and keep the BC as it was. All this is a bit confusing to me, maybe @bxf12315 you have a more accurate idea. 

BTW, I would say if this changes in these classes are needed, we need to remove from this PR the ones related JBPM-9741.

**Comment by bxf12315** [comment]
> @bxf12315, @prashuts I see some changes contained in this PR that are related with by JBPM-9741, and that was the reason to create another PR with those changes related with the Diagram tab at BC.
> What I don't have clear here if the other changes incorporated here (ProcessDiagramWidgetViewImpl.java and ProcessInstanceDiagramViewImpl) are needed to keep working as it was, even the kie-server is showing an svg with the option to see the badges inside the same svg ([kiegroup/droolsjbpm-integration#2484](https://github.com/kiegroup/droolsjbpm-integration/pull/2484)).
> 
> My understanding was that we were going to change the svg served by the kie-server to include the badges and keep the BC as it was. All this is a bit confusing to me, maybe @bxf12315 you have a more accurate idea.
> 
> BTW, I would say if this changes in these classes are needed, we need to remove from this PR the ones related JBPM-9741.

First, JBPM-9741's PR split from this one, second, after we add showBage param in kie-server rest API, the PR is not necessary.

**Pull request closed without merging**
