### PR TITLE
BXMSPROD-1349 point to ScaCap/action-surefire-report@v1.0.10

### PR DESCRIPTION
**Pull request by Ginxo**
https://issues.redhat.com/browse/BXMSPROD-1349

related PR:

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1655
* https://github.com/kiegroup/kie-soup/pull/206
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/523
* https://github.com/kiegroup/drools/pull/3641
* https://github.com/kiegroup/optaplanner/pull/1343
* https://github.com/kiegroup/lienzo-core/pull/145
* https://github.com/kiegroup/lienzo-tests/pull/118
* https://github.com/kiegroup/appformer/pull/1145
* https://github.com/kiegroup/kie-uberfire-extensions/pull/115
* https://github.com/kiegroup/jbpm/pull/1940
* https://github.com/kiegroup/kie-jpmml-integration/pull/55
* https://github.com/kiegroup/droolsjbpm-integration/pull/2499
* https://github.com/kiegroup/kie-wb-playground/pull/107
* https://github.com/kiegroup/kie-wb-common/pull/3643
* https://github.com/kiegroup/drools-wb/pull/1494
* https://github.com/kiegroup/jbpm-designer/pull/905
* https://github.com/kiegroup/jbpm-work-items/pull/198
* https://github.com/kiegroup/jbpm-wb/pull/1496
* https://github.com/kiegroup/optaplanner-wb/pull/393
* https://github.com/kiegroup/kie-wb-distributions/pull/1109
* https://github.com/kiegroup/openshift-drools-hacep/pull/109
* https://github.com/kiegroup/optaweb-employee-rostering/pull/630
* https://github.com/kiegroup/optaweb-vehicle-routing/pull/500

### CODE REVIEW

**Review by mareknovotny — APPROVED** [review]

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
```
2021-05-27T09:52:56.0592847Z [INFO] java.io.IOException: No space left on device
2021-05-27T09:52:56.0594781Z [INFO] 	at java.io.FileOutputStream.writeBytes(Native Method)
2021-05-27T09:52:56.0596653Z [INFO] 	at java.io.FileOutputStream.write(FileOutputStream.java:326)
2021-05-27T09:52:56.0598708Z [INFO] 	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
2021-05-27T09:52:56.0627284Z [INFO] 	at com.google.gwt.dev.util.Util.copyNoClose(Util.java:164)
2021-05-27T09:52:56.0629294Z [INFO] 	at com.google.gwt.core.ext.linker.EmittedArtifact.writeTo(EmittedArtifact.java:202)
2021-05-27T09:52:56.0632541Z [INFO] 	at com.google.gwt.core.ext.linker.impl.StandardLinkerContext.produceOutput(StandardLinkerContext.java:526)
2021-05-27T09:52:56.0635929Z [INFO] 	at com.google.gwt.dev.Link.doProduceOutput(Link.java:413)
2021-05-27T09:52:56.0637100Z [INFO] 	at com.google.gwt.dev.Link.link(Link.java:181)
2021-05-27T09:52:56.0642622Z [INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:232)
2021-05-27T09:52:56.0643960Z [INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:143)
2021-05-27T09:52:56.0645870Z [INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:132)
2021-05-27T09:52:56.0647045Z [INFO] 	at com.google.gwt.dev.Compiler$1.run(Compiler.java:110)
2021-05-27T09:52:56.0649367Z [INFO] 	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
2021-05-27T09:52:56.0651767Z [INFO] 	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
2021-05-27T09:52:56.0653758Z [INFO] 	at com.google.gwt.dev.Compiler.main(Compiler.java:113)
```

it looks like here is space problem for GA @Ginxo

**Comment by Ginxo** [comment]
Free space step added https://github.com/kiegroup/jbpm-wb/pull/1496/commits/6d73f2eae5d1ca9e63f0bc4b2046fd4e01c25860

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
`Caused by: org.eclipse.aether.collection.UnsolvableVersionConflictException: Could not resolve version conflict among [org.webjars.npm:d3-geo-projection:jar:2.5.1 -> org.webjars.npm:d3-array:jar:[1,2), org.webjars.npm:d3-geo-projection:jar:2.5.1 -> org.webjars.npm:d3-geo:jar:[1.10.0,2) -> org.webjars.npm:d3-array:jar:[2.5.0,3)]`
but that is due appformer branch not rebased. Merging.

**Pull request merged**
