### PR TITLE
[Do not merge] Fix for ECJ - GWT conflict

### PR DESCRIPTION
**Pull request by nmirasch**

### CODE REVIEW

**Comment by nmirasch** [comment]
@cristianonicolai @bsremac  @manstis  could you take a look?

**Comment by manstis** [comment]
@nmirasch Just to check, have you verified this fix works at _runtime_ (i.e. you've ```mvn clean process-resources gwt:run``` for both?)

**Comment by nmirasch** [comment]
@manstis tried mvn clean gwt:run. Should I try something else?

**Comment by manstis** [comment]
@nmirasch Nope, if both webapps run OK then that's perfect :-)

**Comment by nmirasch** [comment]
@cristianonicolai  @bsremac @manstis The fix worked fine with jbpm-wb-showcase. just trying with the case jbpm-wb-case-mgmt-showcase, compilation was right but running that I got some errors, let me see if that are related with this fix. This is the error "Error: InvalidBusContentException: Invalid bus content! Expecting content type 'application/json', but got 'text/html;charset=UTF-8!"

**Comment by nmirasch** [comment]
@cristianonicolai @bsremac @manstis false alarm, It was related with my environment. It works fine for both showcases.

**Comment by nmirasch** [comment]
the *real* fix is merged in errai now

**Pull request closed without merging**
