### PR TITLE
JBPM-5873: Add suspend/resume options to task management

### PR DESCRIPTION
**Pull request by rbarriuso**
This PR is made on top of https://github.com/kiegroup/jbpm-wb/pull/677 hence the diff shows the changes from both PRs

### CODE REVIEW

**Comment by rbarriuso** [comment]
Rebased changes after update of https://github.com/kiegroup/jbpm-wb/pull/677

**Comment by cristianonicolai** [comment]
ok to test

**Comment by rbarriuso** [comment]
This PR depends on https://github.com/kiegroup/jbpm-wb/pull/677

**Comment by bsremac** [comment]
@rbarriuso Will only tasks administrator be allowed to suspend/resume tasks i.e. will these options be available only in Tasks Admin perspective?

**Comment by rbarriuso** [comment]
Yes, that's the idea

**Comment by cristianonicolai** [comment]
@rbarriuso suspend/resume are operations available to all task related roles, I'm wondering that it could actually be useful and more consistent if we also add it to the regular task list. wdyt?

**Comment by rbarriuso** [comment]
@cristianonicolai Indeed suspend / resume are also allowed for the owner and potential owners, according to the [operation permission mapping](https://raw.githubusercontent.com/kiegroup/jbpm/master/jbpm-human-task/jbpm-human-task-core/src/main/resources/operations-dsl.mvel). Should I add the buttons then also to the task list perspective?

**Comment by nmirasch** [comment]
@rbarriuso could you rebase, please? Thanks!

**Comment by rbarriuso** [comment]
Rebased

**Comment by rbarriuso** [comment]
This PR also depends on https://github.com/kiegroup/kie-wb-common/pull/769

**Comment by rbarriuso** [comment]
Rebased changes. Added suspend / resume buttons to both task list and task admin views.

**Comment by cristianonicolai** [comment]
@rbarriuso overall looks good to me, only two comments:
- Ideally this PR should be rebased after https://github.com/kiegroup/jbpm-wb/pull/677 is merged so it contains a single commit.
- Would be nice to add some tests around the ResumeActionHasCell and SuspendActionHasCell render methods as these have have important logic to decide if those buttons are visible or not.

**Comment by rbarriuso** [comment]
Working on it

**Comment by rbarriuso** [comment]
Rebased and added extra tests

**Comment by ederign** [comment]
@cristianonicolai can you please take a look on this?

**Comment by cristianonicolai** [comment]
@rbarriuso thanks!

**Pull request merged**
