### PR TITLE
JBPM-6176 - Date range picker to use current time when adding new filter

### PR DESCRIPTION
**Pull request by cristianonicolai**
Move date ranges to its own enum
Use JsInterop for popover and fix container property to properly show arrow

### CODE REVIEW

**Comment by cristianonicolai** [comment]
Depends on https://github.com/AppFormer/uberfire/pull/763

**Comment by cristianonicolai** [comment]
@bsremac the only caveat I see is that when hovering over the calendar picker, date/time will show the value of when the screen was rendered. Once you apply the filter, it then uses the current time.

**Comment by bsremac** [comment]
Jenkins execute full downstream build

**Comment by cristianonicolai** [comment]
@bsremac as for the full downstream build to work we actually need to get https://github.com/kiegroup/jbpm-wb/pull/786 merged first.

**Comment by bsremac** [comment]
Jenkins execute full downstream build

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by cristianonicolai** [comment]
Depends on https://github.com/AppFormer/uberfire/pull/768

**Comment by bsremac** [comment]
@cristianonicolai Noted. As soon as all dependent PRs are merged (at this moment only the last mentioned seems to still be open), I will try to get a full build and test this in more detail.

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by bsremac** [comment]
@cristianonicolai Works as we discussed. Current time is set as upper limit and is stays like that as long as the filter is active.
It's also nice to see that the time filter creation is not dependent on the time the page was rendered.
+1

**Pull request merged**
