### PR TITLE
JBPM-9896 - Enforcer issues fix

### PR DESCRIPTION
**Pull request by hasys**
Part of the ensemble:

**Referenced Pull Requests**:
* https://github.com/kiegroup/kie-wb-common/pull/3682
* https://github.com/kiegroup/jbpm-wb/pull/1513
* https://github.com/kiegroup/kie-wb-distributions/pull/1127
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1766

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by hasys** [comment]
Jenkins retest this

**Review by jomarko — COMMENTED** [review]
both:
jbpm-wb-case-mgmt/jbpm-wb-case-mgmt-showcase/pom.xml
jbpm-wb-showcase/pom.xml

contains a dependency for `errai-cdi-jboss`

In the `kie-wb-common` part of the ensemble, we excluded `xml-apis` from `errai-cdi-jboss`, is it fine to keep it as it is in `jbpm-wb`?

**Comment by hasys** [comment]
Hi @jomarko,

thank you for deep review.

Good question. Exclusions needed only when there is duplication, like `A depends on C` and `B depends on C` in this case we need to exclude one of this `C`. But when it is the only `D depends on C` there is no need to exclude `C` from dependencies.

**Review by jomarko — APPROVED** [review]
thank you @hasys

**Pull request merged**
