### PR TITLE
[WIP] create jbpm-wb-process-instance-migration for both PIM GUI and Services

### PR DESCRIPTION
**Pull request by calvinzhuca**
Signed-off-by: calvin zhu <calvinzhu@hotmail.com>

[Working in Progress] this project will contains both PIM GUI (React) and PIM services. After build it generates a far jar and runs on Thorntail.

### CODE REVIEW

**Comment by kie-ci3** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by nmirasch** [comment]
ok to test

**Comment by calvinzhuca** [comment]
close this WIP PR with a new PR.

**Comment by calvinzhuca** [comment]
new PR: https://github.com/kiegroup/jbpm-wb/pull/1338

**Pull request closed without merging**
