### PR TITLE
JBPM-7807 - Add support for triggering nodes in process instance

### PR DESCRIPTION
**Pull request by cristianonicolai**
Depends on https://github.com/kiegroup/appformer/pull/552

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@nmirasch @jsoltes initial implementation, it allows selecting a node and triggering it but still no interaction in the actual process diagram. I believe is reasonable enough to be merged already. Next step is to add node instances and timers information. The final step will be the actual selection from the diagram, similar to what is done when you manually select a node from the select box.

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by jsoltes** [comment]
@cristianonicolai codewise looks good, lets see if full downstream build produces anything.

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by jsoltes** [comment]
@cristianonicolai looks like there is a compilation error on webapp in full-downstream build...

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by cristianonicolai** [comment]
@jsoltes let me try to address some of these.
1 - I'm appending the node type and id to nodes that do not have an explicit name. The reason why, is that I only use the node type, ex: split, the process might have multiple of these and the users wouldn't know which one to match. I'm not using a sequence number for the specific node type is any better. At least this way, when you expand the node details, you can clearly see that this is the actual id for that node.
2- Goal is that the selection will be interactive, by selecting a process node from the diagram. We could change the order or items in the select, but I find having an alphabetical can be more consistent and easier for users to find the node they need. A process might have many different branches, so deciding on what comes first is not really straightforward.
Will take a look on how to handle items 3, 4 and 5.

**Comment by jsoltes** [comment]
@cristianonicolai thank you. :) 
I have an idea, that would solve the 1. and 2. and isn't that hard to implement. Let's order the selector according to the engine id. And for consistency, could you add it to the human tasks as well? Also, maybe it would look better if the engine id was at the beggining. So instead of 
> bla-4
blabla-2
blablabl-3
bl-1

It would be
> 1-bl
2-blabla
3-blablabl
4-bla

what do you think?

**Comment by cristianonicolai** [comment]
Closing PR as changes are incorporated into https://github.com/kiegroup/jbpm-wb/pull/1250

**Pull request closed without merging**
