### PR TITLE
JBPM-7387: Recover standalone perspectives for process / task forms

### PR DESCRIPTION
**Pull request by pefernan**
Copy of https://github.com/kiegroup/jbpm-wb/pull/1161

@jsoltes @cristianonicolai could you please review?

### CODE REVIEW

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by cristianonicolai** [comment]
@pefernan overall looks good but ideally for master we should reference jbpm jiras instead.

**Comment by pefernan** [comment]
@cristianonicolai done thanks!

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by cristianonicolai** [comment]
@pefernan sorry but I guess commit message would need to change too.

**Comment by pefernan** [comment]
@cristianonicolai sorry! changed commit message

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by cristianonicolai** [comment]
@pefernan thanks, will just wait for a green build to merge.

**Comment by pefernan** [comment]
Unrelated tests failure again...

**Comment by pefernan** [comment]
@cristianonicolai waiting for downstream, but it keeps failing for some unrelated integration tests failures

**Comment by pefernan** [comment]
@cristianonicolai another unrelated test error. I'm going to give it a last try, but if the error persists I'll merge it, we need it for today's cut

**Comment by pefernan** [comment]
@cristianonicolai sorry I had to merge it without waiting for you

**Comment by cristianonicolai** [comment]
@pefernan no worries, I wasn't around anyway.

**Pull request merged**
