### PR TITLE
JBPM-7592 - Add resource type support for .cmmn files

### PR DESCRIPTION
**Pull request by cristianonicolai**
- .cmmn files are listed as Process type in the asset list
- Added upload file support to showcase

### CODE REVIEW

**Comment by mswiderski** [comment]
Jenkins execute full downstream build

**Comment by bsremac** [comment]
@mswiderski Thanks for commenting on the current build issue when trying out _cmmn-itorders_ project. It puts the effort in this PR in the right perspective.
@cristianonicolai @mswiderski I see that opening forms related to the original BPMN2-based _itorders.orderhardware_ process throws an error when the process is replaced with CMMN-based one, which is expected, I suppose. Do we want to leave this as it is for now or maybe remove all the forms from _cmmn-itorders_ which rely on the original process type?

screenshot from 2018-08-14 14-22-43

**Comment by mswiderski** [comment]
@bsremac I would opt at removing the forms from that project

**Comment by cristianonicolai** [comment]
@bsremac based on @mswiderski last comment, are you ok for this to be merged as is?

**Pull request merged**
