### PR TITLE
JBPM-7665: Process Instances: page with vertical scroll bar is flicke…

### PR DESCRIPTION
**Pull request by nmirasch**
…ring after changing window width

### CODE REVIEW

**Comment by nmirasch** [comment]
@cristianonicolai @bsremac I have added the css changes with that fix for the movement of the datagrid lines.

**Comment by bsremac** [comment]
@nmirasch I've noticed one issue around the number of items per page selection. Have a look at the screenshot below.

screenshot from 2018-09-01 17-29-46

**Comment by cristianonicolai** [comment]
same here, the dropdown is somehow hidden now. Although the flickering isn't happening, I can see the table getting pushed to the left as it would allow space for the scroll to appear.

**Comment by nmirasch** [comment]
@cristianonicolai @bsremac  thanks for review it! yes I changed that style to leave space for the dropdown.

**Comment by nmirasch** [comment]
@bsremac @cristianonicolai this fix is tied to the size of page size options. After the meeting I found that maybe the list of options can change maybe have more than 4 options.. If that the case this issue you comment would be still present. Let me give this another try.

**Comment by nmirasch** [comment]
@cristianonicolai @bsremac I found this is the best solution for this 4 page size options i this css. If in the future  we want to allow more options I see different solutions like only let 4 items visible or recalculate dynamically his padding using the configured options size.
Does this make sense? Any thought on this is very welcome. Thanks!

**Comment by bsremac** [comment]
@nmirasch I guess the approach on the sizing of options directly depends on the implementation of https://issues.jboss.org/browse/JBPM-7696.
The currently proposed implementation in open PRs assumes the same options (5,10,15,20). Without any bigger changes in the proposed implementation, this number could potentially increase to 5 options, with the 5th one being an additional value which could be set as a global page size preference.
This is just my current view on where this could go, but I will let @cristianonicolai give the final opinion.

**Comment by cristianonicolai** [comment]
@nmirasch @bsremac just thinking here, what if the pagination select drops up instead of down? That would remove the need to handle this extra padding at the bottom, it would be more friendly to visualize as it could force some scroll to happen when open and also future safe in terms of how many options are listed, wdyt?

**Comment by nmirasch** [comment]
@cristianonicolai  that for sure, would fix the issue I have created this PR https://github.com/kiegroup/appformer/pull/448 with that style change but in the future be have to limit the page sizes visible options anyway. 
@bsremac @cristianonicolai I restored the previous padding value here then that appformer change is needed to merge this pr. Could you take another look?

**Comment by bsremac** [comment]
@nmirasch @cristianonicolai I see no problems with that approach. Interacting with items from the list and changing the pagination are mutually exclusive operations, so I see no problem in selection consuming some of the list space.
Maybe it's worth passing this idea by Liz, just to hear her opinion, since it's a user experience topic above everything else.

**Comment by bsremac** [comment]
@nmirasch Looks good to me.

**Comment by cristianonicolai** [comment]
@nmirasch just to clarify, the selector should already dropup if there is no space right? I'm not sure we need to force the dropup everywhere.

**Comment by nmirasch** [comment]
@cristianonicolai the problem is that drop-down uses the navigation window to know if he has space to be a drop down or drop up and not the div where it is contained. The area that contains the list of items and the pagination bar have to calculate it's own height to be able to remove the space between the list and the bottom bar. When that height is too small to contain the drop-down opened but the navigation window have space to contain that, the page size selector appears as a drop down and includes an hidden scroll that made that effect that @bsremac commented. 

Configuring the page selector always as a dropup removes the scroll problem. Other solution would be to limit the number of items of the selector and include that padding value that allow see that dropdown opened.

**Comment by cristianonicolai** [comment]
ok, got it, so maybe making only the ListTable paginator to always dropup instead of all pagedtables?

**Comment by nmirasch** [comment]
@cristianonicolai sure that makes more sense. I have added a method to pagedTable to configure that and the call to ListTable to only affect this tables.
His PR depends now on https://github.com/kiegroup/appformer/pull/448

**Comment by cristianonicolai** [comment]
@nmirasch can you cherry pick this into 7.11.x please.

**Pull request merged**
