### PR TITLE
JBPM-8655: Task operations are slower after a join was introduced in …

### PR DESCRIPTION
**Pull request by nmirasch**
…"getTaskInstanceById" query

### CODE REVIEW

**Comment by nmirasch** [comment]
depends on https://github.com/kiegroup/jbpm/pull/1516 and  https://github.com/kiegroup/droolsjbpm-integration/pull/1870

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by nmirasch** [comment]
Jenkins execute full downstream build

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by nmirasch** [comment]
Jenkins execute full downstream build

**Pull request merged**
