### PR TITLE
 JBPM-7632 - Add node interaction to diagram

### PR DESCRIPTION
**Pull request by cristianonicolai**
Depends on:
- https://github.com/kiegroup/droolsjbpm-integration/pull/1673
- https://github.com/kiegroup/jbpm/pull/1402
- https://github.com/kiegroup/appformer/pull/585

### CODE REVIEW

**Comment by cristianonicolai** [comment]
Will rebase once https://github.com/kiegroup/jbpm-wb/pull/1259 is merged.

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by jsoltes** [comment]
jenkins please execute full downstream build

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Comment by cristianonicolai** [comment]
Jenkins execute full downstream build

**Pull request merged**
