### PR TITLE
JBPM-6781: reposition date picker popup

### PR DESCRIPTION
**Pull request by michpetrov**
Issue: [JBPM-6781](https://issues.jboss.org/browse/JBPM-6781)

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@bsremac I believe that could be related to having appformer in your local with this change: https://github.com/kiegroup/appformer/pull/257

**Comment by bsremac** [comment]
@cristianonicolai That was the case, but even after building appformer from the current master, the same compilation error is hit again.

**Comment by cristianonicolai** [comment]
@michpetrov could you rebase your PR based on latest master? thanks

**Comment by michpetrov** [comment]
@cristianonicolai done

**Comment by bsremac** [comment]
@michpetrov I still see the issue described in JBPM-6781.
Attached video recording.
[Screencast from 27-03-18 15:54:29.zip](https://github.com/kiegroup/jbpm-wb/files/1852254/Screencast.from.27-03-18.15.54.29.zip)

**Comment by michpetrov** [comment]
@bsremac That's weird, it works for me. I tested it in the jBPM showcase but that shouldn't matter.

**Comment by cristianonicolai** [comment]
I'm running on Firefox 52.6.0 so I can't really reproduce that, @nmirasch any chances you have FF 57 or higher to double check this?

**Comment by cristianonicolai** [comment]
thanks for the fix @michpetrov, please also send a cherry pick to 7.7.x branch.

**Pull request merged**
