### PR TITLE
Constants fix

### PR DESCRIPTION
**Pull request by kmacedovarela**
Job page: fixing translation to Portuguese-BR and fixing a typo on the English version.

### CODE REVIEW

**Comment by kie-ci9** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by cristianonicolai** [comment]
@kmacedovarela thanks for looking into this. The fix for the typo would be fine but changing the translated key needs to be done directly into Zanata https://vendors.zanata.redhat.com/, otherwise, it will be overwritten the next time translations are synced.

**Comment by cristianonicolai** [comment]
@kmacedovarela hi, could you please update the PR so it only includes the commit related to  https://github.com/kiegroup/jbpm-wb/pull/1349/commits/12dce17686bbd7b58226740b34ea1eeba3146145. As I mentioned, the PT Br fixes need to be done in Zanata, otherwise, they will be overridden.

**Comment by kmacedovarela** [comment]
Thanks for the tips and suggestions @cristianonicolai , I adjusted it accordingly. I will update the rest of the translations via Zanata.

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
@kmacedovarela thanks

**Pull request merged**
