### PR TITLE
AF-546: Reduce startup time of AppFormer apps and workbenches

### PR DESCRIPTION
**Pull request by mbarkley**
* Replace @AfterInitialization methods with @PostConstruct
* Remove PlaceManagerActivityService

### CODE REVIEW

**Comment by mbarkley** [comment]
Relates to:
* https://github.com/errai/errai/pull/267
* https://github.com/AppFormer/uberfire/pull/751
* https://github.com/dashbuilder/dashbuilder/pull/340
* https://github.com/kiegroup/guvnor/pull/464
* https://github.com/kiegroup/kie-wb-common/pull/937
* https://github.com/kiegroup/drools-wb/pull/533
* https://github.com/kiegroup/jbpm-form-modeler/pull/117
* https://github.com/kiegroup/kie-wb-distributions/pull/542
* https://github.com/kiegroup/optaplanner-wb/pull/181
* https://github.com/kiegroup/appformer/pull/88

**Comment by mbarkley** [comment]
Jenkins, retest this

**Comment by cristianonicolai** [comment]
@ederign seems like I merged this too early, build is now broken because of the missing related commits. Could you merge all PR's? They seem to be all approved.

**Comment by manstis** [comment]
@cristianonicolai Sorry, I cannot merge them all at the moment since https://github.com/kiegroup/appformer/pull/88 is failing.. @pefernan We're all waiting!! ;-)

**Comment by mbarkley** [comment]
@manstis As it currently doesn't build, I don't think anyone is actively working on the appformer repo at present. Maybe we could merge the rest of the PRs and @pefernan could work off of my PR branch for his fix?

**Comment by manstis** [comment]
@mbarkley We can't merge the other repos until appformer's PR can be merged... I guess @pefernan needs to fix master and then you rebase this PR against master?

**Comment by pefernan** [comment]
@manstis @mbarkley https://github.com/kiegroup/appformer/pull/89 this fixes the issues.. waiting for jenkins greens

**Comment by ederign** [comment]
jenkins retest this

**Comment by ederign** [comment]
trying locally

**Comment by cristianonicolai** [comment]
@manstis @ederign I got most ones that I had permission merged, still missing two PRs:
- https://github.com/AppFormer/uberfire/pull/751
- https://github.com/dashbuilder/dashbuilder/pull/340

**Pull request merged**
